/**
 * Harness E2E for card C2-9: solar_template_beta clone -> one write -> undo
 * -> role checks, disposable-task shape.
 *
 * `server/app.py` does not mount `routers.templates` yet (out of this
 * card's file budget: `files_expected` is frozen to this file + the fence
 * test), so there is no live HTTP surface to drive over `fetch`. Instead
 * each `it()` below spawns a FRESH, short-lived python process (a
 * "disposable task": spun up, does exactly the scenario it was asked for,
 * prints one JSON line, exits -- nothing about it survives past that one
 * call) that imports the real `templates`/`routers.templates` modules
 * directly, the SAME calling convention `server/tests/test_template_*.py`
 * use. Because `templates.py`'s clone/write/undo stores are plain
 * in-process dicts, a brand-new process is naturally hermetic: there is no
 * server to boot, keep alive, or reset between tests, and no shared state
 * for one task to leak into the next.
 *
 * Run:  cd harness && npm test -- tests/solar_template.spec.ts
 */
import { execFileSync } from "node:child_process";
import { mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { afterAll, beforeAll, describe, expect, it } from "vitest";

const HERE = dirname(fileURLToPath(import.meta.url));
// harness/tests -> harness -> repo root -> server
const SERVER_DIR = join(HERE, "..", "..", "server");
const PYTHON = process.env.SOLAR_E2E_PYTHON ?? "python";

// One disposable python task per invocation. Written to a fresh OS temp dir
// at suite start, deleted at suite end -- the driver source itself never
// lives in the repo (files_expected stays exactly the two frozen test files).
const DRIVER_SOURCE = `
"""Disposable task: does exactly the scenario named by its env vars against
the real templates.py / routers.templates modules, prints one JSON line to
stdout, exits. Generated by harness/tests/solar_template.spec.ts."""
import json
import os
import sys

os.environ.setdefault("LEAF_AUTH_LIVE", "0")

SERVER_DIR = os.environ["SOLAR_E2E_SERVER_DIR"]
if SERVER_DIR not in sys.path:
    sys.path.insert(0, SERVER_DIR)

import deps  # noqa: E402
import templates  # noqa: E402
from customization_authority import TenantBinding  # noqa: E402
from routers import templates as templates_router  # noqa: E402

TEMPLATE_ID = "rooftop-standard-string"
TENANT = "tenant-harness-e2e"
PROJECT = "project-harness-e2e"

_OWNER_BINDING = TenantBinding(
    tenant_id=TENANT, subject="author", role="owner", verified=True,
)


def _ctx(role):
    if role == "":
        return deps.TenantContext(TENANT, subject="author", roles=())
    return deps.TenantContext(TENANT, subject="author", roles=(role,))


def _resp_json(resp):
    """Router handlers return either a plain envelope dict (success) or a
    JSONResponse (error) -- normalize both to (status_code, body)."""
    if isinstance(resp, dict):
        return 200, resp
    return resp.status_code, json.loads(resp.body)


def run_flow():
    """clone -> one write -> undo -> idempotent re-undo, as the owner."""
    clone_status, clone_body = _resp_json(templates_router.clone_template_into_project(
        TEMPLATE_ID,
        templates_router.ProjectCloneRequest(project_id=PROJECT),
        tenant=_ctx("owner"),
    ))
    clone_id = clone_body["clone_id"]
    pre_write_content = clone_body["content"]

    write_status, write_body = _resp_json(templates_router.write_project_clone(
        clone_id,
        templates_router.ProjectCloneWriteRequest(
            content={**pre_write_content, "setback_ft": 999},
        ),
        tenant=_ctx("owner"),
    ))
    write_id = write_body["write_id"]
    content_after_write = templates.get_project_clone(clone_id).content

    undo_status, undo_body = _resp_json(templates_router.undo_project_clone_write(
        clone_id,
        templates_router.ProjectCloneUndoRequest(write_id=write_id),
        tenant=_ctx("owner"),
    ))
    content_after_undo = templates.get_project_clone(clone_id).content

    redo_status, redo_body = _resp_json(templates_router.undo_project_clone_write(
        clone_id,
        templates_router.ProjectCloneUndoRequest(write_id=write_id),
        tenant=_ctx("owner"),
    ))

    return {
        "clone": {"status": clone_status, "clone_id": clone_id, "content": pre_write_content},
        "write": {
            "status": write_status,
            "write_id": write_id,
            "content_after_write": content_after_write,
        },
        "undo": {
            "status": undo_status,
            "undone": undo_body["undone"],
            "already_undone": undo_body["already_undone"],
            "content_after_undo": content_after_undo,
        },
        "redo_of_same_write": {
            "status": redo_status,
            "undone": redo_body["undone"],
            "already_undone": redo_body["already_undone"],
        },
        "content_after_undo_matches_pre_write": content_after_undo == pre_write_content,
    }


def run_role(role, action):
    """Seed a clone (+ one write, for the undo case) as owner, then attempt
    \`action\` as \`role\` -- proves the write-grade gate uniformly across
    clone-into-project / write / undo."""
    clone = templates.clone_template_for_project(
        TEMPLATE_ID, tenant_id=TENANT, project_id=PROJECT, version="1.0.0",
        binding=_OWNER_BINDING,
    )
    if action == "clone":
        status, body = _resp_json(templates_router.clone_template_into_project(
            TEMPLATE_ID,
            templates_router.ProjectCloneRequest(project_id=PROJECT),
            tenant=_ctx(role),
        ))
        return {"action": action, "role": role, "status": status, "body": body}
    if action == "write":
        status, body = _resp_json(templates_router.write_project_clone(
            clone.clone_id,
            templates_router.ProjectCloneWriteRequest(content={"setback_ft": 5}),
            tenant=_ctx(role),
        ))
        return {"action": action, "role": role, "status": status, "body": body}
    if action == "undo":
        write = templates.write_project_clone_content(
            clone.clone_id, {**clone.content, "setback_ft": 5}, binding=_OWNER_BINDING,
        )
        status, body = _resp_json(templates_router.undo_project_clone_write(
            clone.clone_id,
            templates_router.ProjectCloneUndoRequest(write_id=write.write_id),
            tenant=_ctx(role),
        ))
        return {"action": action, "role": role, "status": status, "body": body}
    raise SystemExit(f"unknown action {action!r}")


def main():
    mode = os.environ.get("SOLAR_E2E_MODE", "flow")
    if mode == "flow":
        result = run_flow()
    else:
        role = os.environ.get("SOLAR_E2E_ROLE", "owner")
        action = os.environ.get("SOLAR_E2E_ACTION", "write")
        result = run_role(role, action)
    print(json.dumps(result))


if __name__ == "__main__":
    main()
`;

interface FlowResult {
  clone: { status: number; clone_id: string; content: Record<string, unknown> };
  write: { status: number; write_id: string; content_after_write: Record<string, unknown> };
  undo: { status: number; undone: boolean; already_undone: boolean; content_after_undo: Record<string, unknown> };
  redo_of_same_write: { status: number; undone: boolean; already_undone: boolean };
  content_after_undo_matches_pre_write: boolean;
}

interface RoleResult {
  action: "clone" | "write" | "undo";
  role: string;
  status: number;
  body: { error?: { error_code: string; message: string }; clone_id?: string; write_id?: string; undone?: boolean };
}

let workDir: string;
let driverPath: string;

beforeAll(() => {
  workDir = mkdtempSync(join(tmpdir(), "solar-template-e2e-"));
  driverPath = join(workDir, "solar_template_task.py");
  writeFileSync(driverPath, DRIVER_SOURCE, "utf8");
});

afterAll(() => {
  rmSync(workDir, { recursive: true, force: true });
});

function runDisposableTask<T>(env: Record<string, string>): T {
  const stdout = execFileSync(PYTHON, [driverPath], {
    encoding: "utf8",
    timeout: 20_000,
    env: {
      ...process.env,
      LEAF_AUTH_LIVE: "0",
      LEAF_SOLAR_TEMPLATE_BETA_ENABLED: "1",
      SOLAR_E2E_SERVER_DIR: SERVER_DIR,
      ...env,
    },
  });
  const lastLine = stdout.trim().split("\n").pop();
  if (!lastLine) throw new Error(`disposable task produced no output (env=${JSON.stringify(env)})`);
  return JSON.parse(lastLine) as T;
}

function runFlow(): FlowResult {
  return runDisposableTask<FlowResult>({ SOLAR_E2E_MODE: "flow" });
}

function runRole(role: string, action: "clone" | "write" | "undo"): RoleResult {
  return runDisposableTask<RoleResult>({
    SOLAR_E2E_MODE: "role", SOLAR_E2E_ROLE: role, SOLAR_E2E_ACTION: action,
  });
}

describe("solar template E2E: clone -> one write -> undo -> role checks (disposable-task shape)", () => {
  it("clones a template into a project", () => {
    const result = runFlow();
    expect(result.clone.status).toBe(201);
    expect(result.clone.clone_id).toBeTruthy();
    expect(result.clone.content).toBeTruthy();
  });

  it("writes exactly once and the clone reflects that one write", () => {
    const result = runFlow();
    expect(result.write.status).toBe(200);
    expect(result.write.write_id).toBeTruthy();
    expect(result.write.content_after_write.setback_ft).toBe(999);
    expect(result.write.content_after_write.setback_ft).not.toBe(result.clone.content.setback_ft);
  });

  it("undoes the single write back to the exact pre-write content", () => {
    const result = runFlow();
    expect(result.undo.status).toBe(200);
    expect(result.undo.undone).toBe(true);
    expect(result.undo.already_undone).toBe(false);
    expect(result.content_after_undo_matches_pre_write).toBe(true);
    expect(result.undo.content_after_undo).toEqual(result.clone.content);
  });

  it("undo is idempotent: a second undo of the same write is a truthful no-op", () => {
    const result = runFlow();
    expect(result.redo_of_same_write.status).toBe(200);
    expect(result.redo_of_same_write.undone).toBe(true);
    expect(result.redo_of_same_write.already_undone).toBe(true);
  });

  it("each disposable task starts from a clean slate -- two flows never collide on clone id", () => {
    const first = runFlow();
    const second = runFlow();
    expect(first.clone.clone_id).not.toBe(second.clone.clone_id);
    expect(second.clone.status).toBe(201);
    expect(second.content_after_undo_matches_pre_write).toBe(true);
  });

  it.each(["owner", "editor"])("role check: %s can clone into a project", (role) => {
    const result = runRole(role, "clone");
    expect(result.status).toBe(201);
    expect(result.body.clone_id).toBeTruthy();
  });

  it.each(["owner", "editor"])("role check: %s can write to a clone they hold", (role) => {
    const result = runRole(role, "write");
    expect(result.status).toBe(200);
    expect(result.body.write_id).toBeTruthy();
  });

  it.each(["owner", "editor"])("role check: %s can undo their own write", (role) => {
    const result = runRole(role, "undo");
    expect(result.status).toBe(200);
    expect(result.body.undone).toBe(true);
  });

  it.each(["viewer", ""])("role check: %s is denied clone-into-project", (role) => {
    const result = runRole(role, "clone");
    expect(result.status).toBe(403);
    expect(result.body.error?.error_code).toBe("FORBIDDEN");
  });

  it.each(["viewer", ""])("role check: %s is denied write", (role) => {
    const result = runRole(role, "write");
    expect(result.status).toBe(403);
    expect(result.body.error?.error_code).toBe("FORBIDDEN");
  });

  it.each(["viewer", ""])("role check: %s is denied undo (same write-grade gate as write)", (role) => {
    const result = runRole(role, "undo");
    expect(result.status).toBe(403);
    expect(result.body.error?.error_code).toBe("FORBIDDEN");
  });
});
