import { useEffect, useRef, useState } from 'react'

// "Author a tool" — a text description -> POST /api/author -> a generated
// tool card + code preview, added to the tool list so it's immediately
// runnable (CONTRACT §4 /api/author, §6 item 4).
//
// Real authoring runs an agent and takes ~1–2 min, so Generate becomes a calm
// long-running state: plain ticking text ("authoring with the agent · 34s"),
// NO spinner. On success we surface PROVENANCE — authored-by-agent vs templated,
// derived from the response `source` (sibling contract: top-level
// "harness"|"template"), with an honest "agent unavailable — templated fallback"
// when the harness was configured but unreachable — plus any advisory
// static-scan flags as calm amber tags.
//
// `seed` (+ `seedSignal`) is the build-lane hook: when the nl-prompt router
// classifies a prompt as lane:"build", App prefills this description here so the
// author flow opens ready to generate. seedSignal bumps on each route so the
// same text can be re-seeded.
const EXAMPLES = [
  'count panels within 18in of the roof edge',
  'measure the total area of all panels',
  'select everything on the Panel Groups layer',
]

// Derive the honest provenance from the /api/author response. The sibling
// contract adds top-level `source` + `static_scan`; until it lands we fall back
// to the signals the current backend already emits (a preview fallback marker +
// tool.provenance.static_scan), so this reads correctly either way.
function readProvenance(res) {
  const preview = res?.preview || ''
  // The templated-fallback marker the backend prepends when the harness was
  // configured but unreachable — the honest "agent unavailable" signal.
  const fallback = /\[harness unreachable|templated fallback/i.test(preview) || res?.fallback === true
  const source = res?.source || null
  // Agent-authored ONLY when the server says source:"harness" and it wasn't a fallback.
  const agent = source === 'harness' && !fallback
  const scan = Array.isArray(res?.static_scan)
    ? res.static_scan
    : (res?.tool?.provenance?.static_scan || [])
  return { source, agent, fallback, scan }
}

function ProvenanceBadge({ prov }) {
  if (prov.fallback) {
    return (
      <span className="badge user" title="The authoring agent was unreachable — Leaf fell back to a templated tool.">
        agent unavailable — templated fallback
      </span>
    )
  }
  if (prov.agent) {
    return <span className="badge agent" title="Generated by the authoring agent (harness).">authored by agent</span>
  }
  return <span className="badge" title="Generated from a built-in template.">templated</span>
}

export default function AuthorPanel({ onAuthor, onUseAuthored, seed, seedSignal }) {
  const [desc, setDesc] = useState('')
  const [busy, setBusy] = useState(false)
  const [elapsedMs, setElapsedMs] = useState(0)
  const [err, setErr] = useState(null)
  const [authored, setAuthored] = useState(null)
  const lastSignal = useRef(null)
  const startRef = useRef(null)

  // Prefill from a build-lane route (only when the signal changes, so manual
  // edits are never clobbered by a re-render).
  useEffect(() => {
    if (seedSignal != null && seedSignal !== lastSignal.current) {
      lastSignal.current = seedSignal
      if (seed) setDesc(seed)
    }
  }, [seed, seedSignal])

  // Calm ticking wall-clock while authoring — real elapsed, no spinner.
  useEffect(() => {
    if (!busy) return
    startRef.current = Date.now()
    setElapsedMs(0)
    const id = setInterval(() => setElapsedMs(Date.now() - startRef.current), 250)
    return () => clearInterval(id)
  }, [busy])

  async function submit() {
    if (!desc.trim()) return
    setBusy(true); setErr(null); setAuthored(null)
    try {
      const res = await onAuthor(desc.trim())
      setAuthored(res)
    } catch (e) {
      setErr(String(e.message || e))
    } finally {
      setBusy(false)
    }
  }

  const secs = Math.floor(elapsedMs / 1000)
  const prov = authored ? readProvenance(authored) : null

  return (
    <div className="author-panel author-inner">
      <p className="panel-sub">Describe a CAD tool in plain English. Leaf generates it and adds it to the catalog.</p>
      <textarea
        value={desc}
        onChange={(e) => setDesc(e.target.value)}
        placeholder="e.g. count panels within 18in of the roof edge"
        rows={3}
        disabled={busy}
      />
      <div className="examples">
        {EXAMPLES.map((ex) => (
          <button key={ex} className="chip" onClick={() => setDesc(ex)} disabled={busy}>{ex}</button>
        ))}
      </div>
      <button className="btn primary" disabled={busy || !desc.trim()} onClick={submit}>
        {busy ? 'authoring…' : 'Generate tool'}
      </button>
      {busy && (
        <div className="authoring">
          authoring with the agent · {secs}s
          <span className="dim"> · real authoring takes ~1–2 min · safe to wait</span>
        </div>
      )}
      {err && <div className="inline-error">{err}</div>}

      {authored && (
        <div className="authored">
          <div className="authored-head">
            <span className="tool-name">{authored.tool.name}</span>
            <ProvenanceBadge prov={prov} />
          </div>
          {prov.scan.length > 0 && (
            <div className="scan-flags" title="Advisory static-scan findings — non-blocking.">
              {prov.scan.map((f) => (
                <span key={f} className="scan-flag">{f}</span>
              ))}
            </div>
          )}
          <p className="authored-desc">{authored.preview || authored.tool.description}</p>
          <pre className="code"><code>{authored.code}</code></pre>
          <button className="btn" onClick={() => onUseAuthored(authored.tool)}>
            Run it now
          </button>
        </div>
      )}
    </div>
  )
}
