"""Studio's four probe calculations against the licensed plugin, computed.

Three layers, all hermetic and none of them skipping:

  1. The C# number formatters this port depends on that the NEC port did not
     already need: the "R" shortest round-trippable form, and the round-half-to
     EVEN rule `(int)Math.Round` uses inside BucketCoordinate, which is the
     opposite of the away-from-zero rule the "F<n>" form uses one file away.
  2. The plugin's OWN unit tests, ported case for case from
     Tests/Tests/PanelGroupTradeCalculatorTests.cs,
     Tests/Tests/LeafTorqueTubeShadeTests.cs, Tests/Tests/LeafShadeLimitTests.cs,
     Tests/Tests/LeafShadeLimitExternalReferenceTests.cs and
     Tests/Tests/ProjectSummaryReportTests.cs (read 2026-09-22 at
     C:/tmp/solar-parity/wt-b25-s17).
  3. Every probe in the four licensed DEMO captures, reproduced by RUNNING
     Studio's scenario lists through server/solar_probe_calcs.py. The captures
     are the licensed AutoCAD 2025 run of 2026-09-23 and are COMMITTED at
     docs/parity/evidence/probes/demo-probes-20260923, so this layer reads the
     artifact itself rather than a transcription and every runner carries it.
     Each file is asserted whole (the generated text equals the capture) and
     then probe by probe, so a failure names the scenario that moved.

Line endings, and why the whole-file assertion normalizes them. The plugin
writes CRLF and this port writes CRLF, which `test_generated_files_use_the
_plugins_crlf` asserts on the GENERATED bytes. The committed capture is a
tracked text file, so git's checkout translation (core.autocrlf on this host)
decides its on-disk line endings, and comparing against it byte for byte would
be asserting a git setting rather than a parity fact. So the capture comparison
normalizes CRLF to LF on both sides, and the CRLF contract is proven separately
where it is actually ours to hold.

Nothing here feeds a captured value back into the port: solar_probe_calcs.py
computes every number and renders every string, and these are the assertions it
must meet.
"""

from __future__ import annotations

import importlib.util
import json
import math
import os
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[2]


def _load(name, path):
    spec = importlib.util.spec_from_file_location(name, path)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


calcs = _load("solar_probe_calcs", ROOT / "server" / "solar_probe_calcs.py")
probes = _load("solar_probe_calcs_probes", ROOT / "scripts" / "solar_probe_calcs_probes.py")

# The licensed capture is committed in this repo, so every runner carries it.
DEFAULT_REFERENCE_DIR = ROOT / "docs/parity/evidence/probes/demo-probes-20260923"
REFERENCE_DIR = Path(os.environ.get("LEAF_SOLAR_W3_PROBE_CALCS_REF",
                                    str(DEFAULT_REFERENCE_DIR)))

ALL_FILES = tuple(name for demo in sorted(probes.DEMOS)
                  for name in probes.file_names(demo))
CROSS_AXIS_M = probes.SHADELIMIT_CROSS_AXIS_M


def reference_text(name):
    """The committed capture, with the checkout's line endings normalized."""
    return REFERENCE_DIR.joinpath(name).read_bytes().decode("utf-8").replace("\r\n", "\n")


def generated_text(name):
    """Studio's own rendering of one file, computed from its scenario list."""
    return probes.build(probes.FILE_DEMOS[name])[name]


def reference_rows(name):
    """The capture's CSV rows as dicts, header row giving the field names."""
    lines = [line for line in reference_text(name).split("\n")
             if line and not line.startswith("#")]
    header = lines[0].split(",")
    return [dict(zip(header, line.split(","))) for line in lines[1:]]


# --------------------------------------------------------------------------- #
# The capture is committed, and it is what layer 3 reads
# --------------------------------------------------------------------------- #
def test_every_licensed_file_is_committed():
    present = sorted(path.name for path in REFERENCE_DIR.iterdir() if path.is_file())
    assert present == sorted(ALL_FILES)


# --------------------------------------------------------------------------- #
# Layer 1: the C# formatters this port adds
# --------------------------------------------------------------------------- #
@pytest.mark.parametrize("value,text", [
    (0.0, "0"),
    (-0.0, "-0"),
    (1.0, "1"),
    (2.0, "2"),
    (5.0, "5"),
    (-30.0, "-30"),
    (90.0, "90"),
    (0.08, "0.08"),
    (0.13, "0.13"),
    (2.1, "2.1"),
    (89.9, "89.9"),
    (0.12660254037844387, "0.12660254037844387"),
    (0.9999992384566438, "0.9999992384566438"),
])
def test_format_roundtrip_is_csharps_r_format(value, text):
    """C# "R" prints an integral double with no fraction and never pads."""
    assert calcs.format_roundtrip(value) == text


@pytest.mark.parametrize("value,text", [
    (float("nan"), "NaN"),
    (float("inf"), "Infinity"),
    (float("-inf"), "-Infinity"),
])
def test_format_roundtrip_names_the_non_finite_values_csharps_way(value, text):
    assert calcs.format_roundtrip(value) == text


@pytest.mark.parametrize("value,decimals,text", [
    (30.0, 0, "30"),
    (0.5, 12, "0.500000000000"),
    (2.1, 9, "2.100000000"),
    (float("nan"), 9, "NaN"),
])
def test_format_fixed_is_the_plugins_fixed_form(value, decimals, text):
    assert calcs.format_fixed(value, decimals) == text


@pytest.mark.parametrize("value,values,expected", [
    # Spacing 2 puts these exactly on .5, where C#'s Math.Round goes to the
    # EVEN neighbour. Away-from-zero would answer 1 and 2 instead of 0 and 2.
    (1.0, (0.0, 2.0), 0),
    (3.0, (0.0, 2.0), 2),
    (5.0, (0.0, 2.0), 2),
    # A single distinct value, and a spacing under the 1e-6 floor, both bucket 0.
    (5.0, (5.0,), 0),
    (1.0, (0.0, 1e-9), 0),
])
def test_bucket_coordinate_rounds_half_to_even(value, values, expected):
    assert calcs.bucket_coordinate(value, values) == expected


# --------------------------------------------------------------------------- #
# Layer 2: the plugin's own NUnit cases
# PanelGroupTradeCalculatorTests.cs:485-581
# --------------------------------------------------------------------------- #
def test_snake_order_null_or_empty_returns_the_same_object():
    assert calcs.snake_order(None) is None
    empty = []
    assert calcs.snake_order(empty) is empty


def test_snake_order_single_panel_returns_the_same_object():
    panels = [calcs.TradePanel("a", 0, 0)]
    result = calcs.snake_order(panels)
    assert result is panels
    assert len(result) == 1


def test_snake_order_with_row_col_alternates_direction():
    panels = [calcs.TradePanel("r%dc%d" % (row, col), col, row, row, col)
              for row in range(3) for col in range(3)]
    result = [panel.handle for panel in calcs.snake_order(panels)]
    assert result == ["r0c0", "r0c1", "r0c2",
                      "r1c2", "r1c1", "r1c0",
                      "r2c0", "r2c1", "r2c2"]


def test_snake_order_without_row_col_uses_coordinate_bucketing():
    panels = [calcs.TradePanel("a", 0, 0), calcs.TradePanel("b", 5, 0),
              calcs.TradePanel("c", 10, 0), calcs.TradePanel("d", 0, 10),
              calcs.TradePanel("e", 5, 10), calcs.TradePanel("f", 10, 10)]
    result = [panel.handle for panel in calcs.snake_order(panels)]
    assert result == ["a", "b", "c", "f", "e", "d"]


@pytest.mark.parametrize("value,expected", [(0, 0), (10, 1), (20, 2), (30, 3)])
def test_bucket_coordinate_evenly_spaced_returns_index(value, expected):
    assert calcs.bucket_coordinate(value, (0, 10, 20, 30)) == expected


# LeafTorqueTubeShadeTests.cs:73-213
def test_self_shade_zero_tube_radius_returns_zero():
    assert calcs.rear_self_shade_fraction(2.1, 0.0, 0.0, 0.0, 30.0) == 0.0


def test_self_shade_zero_tilt_equals_tube_diameter_over_cross_axis():
    """At tilt 0 the gaps contribute nothing, so only the diameter counts."""
    value = calcs.rear_self_shade_fraction(2.1, 0.075, 0.05, 0.05, 0.0)
    assert value == pytest.approx((2 * 0.075) / 2.1, abs=1e-9)


def test_self_shade_30deg_150mm_tube_50mm_gaps_matches_closed_form():
    band = 2 * 0.075 + (0.05 + 0.05) * 0.5
    value = calcs.rear_self_shade_fraction(2.1, 0.075, 0.05, 0.05, 30.0)
    assert value == pytest.approx(band / 2.1, abs=1e-9)


def test_self_shade_30deg_differs_from_flat_tracker_by_at_least_one_percent():
    """The plugin's Q14 acceptance criterion, carried over as an assertion."""
    with_tube = calcs.rear_self_shade_fraction(2.1, 0.075, 0.05, 0.05, 30.0)
    flat = calcs.rear_self_shade_fraction(2.1, 0.0, 0.0, 0.0, 30.0)
    assert with_tube - flat >= 0.01


@pytest.mark.parametrize("tilt_deg", [0.0, 15.0, 30.0, 45.0, 60.0])
def test_self_shade_is_monotonic_in_tilt(tilt_deg):
    at_tilt = calcs.rear_self_shade_fraction(2.1, 0.075, 0.05, 0.05, tilt_deg)
    at_zero = calcs.rear_self_shade_fraction(2.1, 0.075, 0.05, 0.05, 0.0)
    assert at_tilt >= at_zero - 1e-12


def test_self_shade_clamps_at_one_when_the_band_exceeds_the_cross_axis():
    assert calcs.rear_self_shade_fraction(0.5, 1.0, 0.0, 0.0, 0.0) == 1.0


def test_self_shade_negative_tilt_takes_the_absolute_value():
    positive = calcs.rear_self_shade_fraction(2.1, 0.075, 0.05, 0.05, 30.0)
    negative = calcs.rear_self_shade_fraction(2.1, 0.075, 0.05, 0.05, -30.0)
    assert negative == positive


def test_self_shade_non_positive_cross_axis_returns_zero_rather_than_dividing():
    """The C# guard clause; the port answers 0 instead of raising on 0 width."""
    assert calcs.rear_self_shade_fraction(0.0, 0.08, 0.05, 0.05, 45.0) == 0.0
    assert calcs.rear_self_shade_fraction(-1.0, 0.08, 0.05, 0.05, 45.0) == 0.0


# LeafShadeLimitTests.cs:66-303
def test_max_gcr_for_sla_zero_sla_returns_zero():
    assert calcs.max_gcr_for_sla(0.0, 60.0) == pytest.approx(0.0, abs=1e-9)


def test_max_gcr_for_sla_closed_form_reference_15deg_60tilt():
    """g = tan(SLA) / (sin(t) + tan(SLA) * cos(t)), a trig identity, not the impl."""
    tan_sla = math.tan(15.0 * math.pi / 180.0)
    expected = tan_sla / (math.sin(60.0 * math.pi / 180.0)
                          + tan_sla * math.cos(60.0 * math.pi / 180.0))
    assert calcs.max_gcr_for_sla(15.0, 60.0) == pytest.approx(expected, abs=1e-9)


@pytest.mark.parametrize("sla,tilt", [
    (5.0, 45.0), (10.0, 50.0), (15.0, 55.0), (20.0, 60.0),
    (25.0, 60.0), (30.0, 52.0), (12.3, 48.7), (8.0, 55.0),
])
def test_max_gcr_for_sla_round_trips_through_the_forward_formula(sla, tilt):
    gcr = calcs.max_gcr_for_sla(sla, tilt)
    assert calcs.compute_shade_limit_angle(gcr, tilt) == pytest.approx(sla, abs=1e-6)


@pytest.mark.parametrize("sla,tilt", [(-1.0, 60.0), (91.0, 60.0),
                                      (15.0, 0.0), (15.0, 90.0)])
def test_max_gcr_for_sla_refuses_arguments_outside_its_domain(sla, tilt):
    with pytest.raises(calcs.ShadeLimitError):
        calcs.max_gcr_for_sla(sla, tilt)


def test_min_pitch_for_sla_equals_cross_axis_over_max_gcr():
    gcr = calcs.max_gcr_for_sla(10.0, 55.0)
    pitch = calcs.min_pitch_for_sla(10.0, 2.100, 55.0)
    assert pitch == pytest.approx(2.100 / gcr, abs=1e-9)


def test_min_pitch_for_sla_refuses_a_non_positive_cross_axis():
    with pytest.raises(calcs.ShadeLimitError):
        calcs.min_pitch_for_sla(10.0, 0.0, 55.0)


@pytest.mark.parametrize("gcr,tilt", [(0.0, 60.0), (1.0, 60.0),
                                      (0.5, 0.0), (0.5, 90.0)])
def test_compute_shade_limit_angle_refuses_arguments_outside_its_domain(gcr, tilt):
    with pytest.raises(calcs.ShadeLimitError):
        calcs.compute_shade_limit_angle(gcr, tilt)


# LeafShadeLimitExternalReferenceTests.cs:67-101. Lorenzo 2011 Eq. 6 anchors,
# each derivable from a trig identity rather than from the implementation.
@pytest.mark.parametrize("gcr,tilt,sla", [
    (0.5, 60.0, 30.0),
    (1.0 / math.sqrt(2.0), 45.0, 45.0),
    (math.sqrt(3.0) / 2.0, 30.0, 60.0),
])
def test_compute_shade_limit_angle_matches_the_external_anchors(gcr, tilt, sla):
    assert calcs.compute_shade_limit_angle(gcr, tilt) == pytest.approx(sla, abs=1e-9)


def test_auto_calculate_matches_the_nrel_spa_reference_point():
    """Reda and Andreas 2004 Table 2: Denver, 39.888 degrees elevation.

    Spencer 1971 is the lower-accuracy model, so the plugin's own tolerance of
    one degree is the one used here.
    """
    result = calcs.shade_limit_auto_calculate(
        39.742476, -105.1786, calcs.utc(2003, 10, 17, 19, 30, 30), 2.100, 60.0)
    assert result.is_daytime is True
    assert result.sun_elevation_deg == pytest.approx(39.888, abs=1.0)


@pytest.mark.parametrize("lat,moment,elevation", [
    (0.0, (2024, 3, 20, 12, 7, 0), 90.0),
    (40.0, (2024, 6, 20, 12, 0, 0), 73.45),
    (40.0, (2024, 12, 21, 12, 2, 0), 26.55),
])
def test_auto_calculate_matches_the_textbook_solar_noon_elevation(lat, moment, elevation):
    """elev_noon = 90 - |lat - declination| (Iqbal 1983 section 4.2)."""
    result = calcs.shade_limit_auto_calculate(lat, 0.0, calcs.utc(*moment), 2.100, 60.0)
    assert result.sun_elevation_deg == pytest.approx(elevation, abs=1.5)


def test_auto_calculate_winter_solstice_noon_forty_north_produces_the_expected_pitch():
    result = calcs.shade_limit_auto_calculate(
        40.0, 0.0, calcs.utc(2024, 12, 21, 12, 2, 0), 2.100, 60.0)
    assert 0.40 <= result.max_gcr <= 0.50
    assert 4.3 <= result.min_pitch_m <= 5.3


def test_auto_calculate_sun_below_horizon_returns_no_pitch():
    result = calcs.shade_limit_auto_calculate(
        40.0, 0.0, calcs.utc(2024, 12, 21, 0, 0, 0), 2.100, 60.0)
    assert result.is_daytime is False
    assert result.sun_elevation_deg <= 0.0
    assert result.max_gcr == 0.0
    assert math.isinf(result.min_pitch_m)


@pytest.mark.parametrize("cross_axis,tilt", [(2.1, 0.0), (2.1, 90.0), (0.0, 55.0)])
def test_auto_calculate_refuses_an_invalid_tilt_or_cross_axis(cross_axis, tilt):
    with pytest.raises(calcs.ShadeLimitError):
        calcs.shade_limit_auto_calculate(40.0, 0.0, calcs.utc(2024, 6, 20, 12, 0, 0),
                                         cross_axis, tilt)


# ProjectSummaryReportTests.cs:125-162, the ToJson and ToCsv half.
def _roundtrip_fixture():
    summary = calcs.ProjectSummary(
        panel_count=100, inverter_count=2, string_count=8, total_dc_kwp=40.0,
        total_ac_kw=33.0, dc_ac_ratio=1.21, total_trunk_length=150.0,
        total_branch_length=90.0, critical_findings=1, warning_findings=2,
        info_findings=3)
    summary.strings_by_length[12] = 4
    summary.strings_by_length[14] = 4
    summary.largest_cable_sizes.append("10 AWG x8")
    return summary


def test_project_summary_json_round_trip_preserves_key_fields():
    document = json.loads(calcs.project_summary_to_json(_roundtrip_fixture()))
    assert document["PanelCount"] == 100
    assert document["InverterCount"] == 2
    assert document["StringCount"] == 8
    assert document["TotalDcKwp"] == 40.0
    assert document["DcAcRatio"] == pytest.approx(1.21, abs=1e-6)
    assert document["StringsByLength"]["12"] == 4
    assert document["LargestCableSizes"][0] == "10 AWG x8"


@pytest.mark.parametrize("row", ["PanelCount,100", "InverterCount,2",
                                 "DcAcRatio,1.210", "StringsOfLength_12,4",
                                 "CableSize_1,10 AWG x8"])
def test_project_summary_csv_carries_the_plugins_rows(row):
    assert row + calcs.CRLF in calcs.project_summary_to_csv(_roundtrip_fixture())


# --------------------------------------------------------------------------- #
# Layer 3: every probe in the licensed capture, reproduced by computing it
# --------------------------------------------------------------------------- #
@pytest.mark.parametrize("name", ALL_FILES)
def test_generated_file_reproduces_the_licensed_capture(name):
    assert generated_text(name).replace("\r\n", "\n") == reference_text(name)


@pytest.mark.parametrize("name", ALL_FILES)
def test_generated_files_use_the_plugins_crlf(name):
    """The plugin writes CRLF, its CSVs end with one and its JSON does not."""
    text = generated_text(name)
    assert "\n" not in text.replace("\r\n", "")
    assert text.endswith(calcs.CRLF) == name.endswith(".csv")


SNAKEORDER_PROBES = json.loads(reference_text("leafsnakeorder_probes.json"))


@pytest.mark.parametrize("probe", SNAKEORDER_PROBES,
                         ids=[probe["Name"] for probe in SNAKEORDER_PROBES])
def test_snake_order_reproduces_each_licensed_probe(probe):
    """The capture's INPUT panels are re-run through the port; only the inputs
    are read from the file, and the handle order and the reference-equality flag
    are both computed."""
    panels = None if probe["InputPanels"] is None else [
        calcs.TradePanel(entry["Handle"], entry["X"], entry["Y"],
                         entry["Row"], entry["Col"])
        for entry in probe["InputPanels"]]
    result = calcs.snake_order(panels)
    handles = None if result is None else [panel.handle for panel in result]
    assert handles == probe["OutputHandles"]
    assert (result is panels) == probe["Unchanged"]
    assert (panels is None) == probe["InputIsNull"]


TORQUESHADE_ROWS = reference_rows("leaftorqueshade_demo.csv")


@pytest.mark.parametrize("row", TORQUESHADE_ROWS,
                         ids=[row["Label"] for row in TORQUESHADE_ROWS])
def test_torque_shade_reproduces_each_licensed_probe(row):
    fraction = calcs.rear_self_shade_fraction(
        float(row["CrossAxisM"]), float(row["RadiusM"]),
        float(row["TopGapM"]), float(row["BotGapM"]), float(row["TiltDeg"]))
    assert calcs.format_roundtrip(fraction) == row["Fraction"]


SHADELIMIT_ROWS = reference_rows("leafshadelimit_demo.csv")


@pytest.mark.parametrize("row", SHADELIMIT_ROWS,
                         ids=[row["label"] for row in SHADELIMIT_ROWS])
def test_shade_limit_reproduces_each_licensed_probe(row):
    """Each block recomputes its own columns from the row's inputs.

    Block A's GCR and target SLA and block C's timestamp are scenario INPUTS, so
    they come from Studio's own list, never from the capture: the file renders
    its gcr_in at twelve decimals, and re-running the forward formula on that
    ROUNDED value would answer 59.999999999950 where the plugin answers 60. The
    rendering of the input is asserted too, so nothing about it goes unchecked.
    Block B's target SLA is genuinely in the file, in the column the other two
    blocks use for an output.
    """
    tilt_deg = float(row["tilt_deg"])
    if row["block"] == "A":
        anchors = {name: (gcr, sla) for name, gcr, _, sla in probes.SHADELIMIT_ANCHORS}
        gcr, expected_sla = anchors[row["label"]]
        assert calcs.format_fixed(gcr, 12) == row["gcr_in"]
        assert calcs.format_fixed(
            calcs.compute_shade_limit_angle(gcr, tilt_deg), 12) == row["sla_target_deg"]
        max_gcr = calcs.max_gcr_for_sla(expected_sla, tilt_deg)
        assert calcs.format_fixed(max_gcr, 12) == row["max_gcr"]
        assert calcs.format_fixed(calcs.compute_shade_limit_angle(max_gcr, tilt_deg),
                                  12) == row["sla_reconstructed_deg"]
        assert calcs.format_fixed(
            calcs.min_pitch_for_sla(expected_sla, CROSS_AXIS_M, tilt_deg),
            9) == row["min_pitch_m"]
    elif row["block"] == "B":
        sla_target = float(row["sla_target_deg"])
        max_gcr = calcs.max_gcr_for_sla(sla_target, tilt_deg)
        assert calcs.format_fixed(max_gcr, 12) == row["max_gcr"]
        assert calcs.format_fixed(calcs.compute_shade_limit_angle(max_gcr, tilt_deg),
                                  12) == row["sla_reconstructed_deg"]
        assert calcs.format_fixed(
            calcs.min_pitch_for_sla(sla_target, CROSS_AXIS_M, tilt_deg),
            9) == row["min_pitch_m"]
    else:
        moment = dict(probes.SHADELIMIT_AUTOCALCS)[row["label"]]
        result = calcs.shade_limit_auto_calculate(
            probes.SHADELIMIT_LAT_DEG, probes.SHADELIMIT_LON_DEG, moment,
            CROSS_AXIS_M, probes.SHADELIMIT_MAX_TILT_DEG)
        assert calcs.format_fixed(result.sun_elevation_deg, 12) == row["sla_target_deg"]
        assert calcs.format_fixed(result.max_gcr, 12) == row["max_gcr"]
        assert calcs.format_fixed(result.min_pitch_m, 9) == row["min_pitch_m"]
        assert calcs.format_fixed(result.sun_elevation_deg, 6) == row["sun_elev_deg"]
        assert calcs.format_fixed(result.sun_azimuth_deg, 6) == row["sun_az_deg"]
        assert ("1" if result.is_daytime else "0") == row["is_daytime"]


PROJECTSUMMARY_LABELS = tuple(label for label, _ in probes.PROJECTSUMMARY_FIXTURES)


@pytest.mark.parametrize("label", PROJECTSUMMARY_LABELS)
def test_project_summary_csv_reproduces_each_licensed_row(label):
    """Row by row, so a precision or sort-order drift names the metric."""
    summary = dict(probes.PROJECTSUMMARY_FIXTURES)[label]()
    computed = calcs.project_summary_to_csv(summary).replace("\r\n", "\n").split("\n")
    expected = reference_text("leafprojectsummary_demo_%s.csv" % label).split("\n")
    assert len(computed) == len(expected)
    for computed_row, expected_row in zip(computed, expected):
        assert computed_row == expected_row


@pytest.mark.parametrize("label", PROJECTSUMMARY_LABELS)
def test_project_summary_json_reproduces_each_licensed_key(label):
    """Key by key AND in order, because the JSON's insertion order is the
    property the CSV's ascending sort is deliberately asymmetric to."""
    summary = dict(probes.PROJECTSUMMARY_FIXTURES)[label]()
    computed = json.loads(calcs.project_summary_to_json(summary))
    expected = json.loads(reference_text("leafprojectsummary_demo_%s.json" % label))
    assert list(computed) == list(expected)
    for key in expected:
        assert computed[key] == expected[key]
        if isinstance(expected[key], dict):
            assert list(computed[key]) == list(expected[key])
