"""Studio's KML and LandXML writers and readers against the licensed plugin, computed.

Three layers, all hermetic and none of them skipping:

  1. Every file the five licensed DEMOs wrote (LEAFKMLEXPORTDEMO,
     LEAFKMLEXPORTFMTDEMO, LEAFKMLIMPORTDEMO, LEAFLANDXMLDEMO and
     LEAFIMPORTLANDXMLDEMO), reproduced by RUNNING Studio's fixtures through
     server/solar_geo_formats.py. The captures are the licensed AutoCAD 2025 run
     of 2026-09-23 and are COMMITTED at
     docs/parity/evidence/probes/demo-probes-20260923, so this layer reads the
     artifact itself. Each file is asserted whole, and each CSV row by row (one
     test per licensed row, collected from the committed file), so a failure
     names the row.
  2. The format branches the plugin's writers and readers take, one behaviour
     per test: altitude omission, ring closure and its epsilon, missing names,
     null polygons, G17, escaping, the pole guard, namespace stripping, the
     silent skip of malformed LandXML points, the Delaunay in-circle test, and
     the IDW resampler.
  3. Hostile XML: a DOCTYPE, internal and external entities, parameter
     entities, an undefined entity, unbound prefixes, depth and size bounds.
     Every XML entry point refuses them before any expansion can happen.

Two inputs that are not geometry. The LandXML header carries DateTime.UtcNow,
which the scenario pins (solar_geo_formats_probes.LANDXML_UTC_NOW). The import
report's `#` line names the file the importer read, so the whole-file check
passes the path the licensed run read (LICENSED_KML_PATH); the rows below it
are asserted independently of that line.

Line endings. The plugin writes CRLF and this port writes CRLF, which
`test_generated_bytes_carry_the_plugins_encoding_and_crlf` asserts on the
GENERATED bytes. The committed capture is a tracked text file, so the whole-file
assertion normalizes CRLF to LF on both sides rather than asserting a git
setting. The byte order mark is not a line ending, so that assertion keeps it.

C# exception types map to Python ones: ArgumentNullException to TypeError,
ArgumentException to ValueError (KmlArgumentError for the pole guard),
XmlException and FormatException to GeoFormatError.
"""

from __future__ import annotations

from datetime import datetime, timedelta, timezone
import functools
import importlib.util
import math
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[2]


def _load(name, path):
    spec = importlib.util.spec_from_file_location(name, path)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


engine = _load("solar_geo_formats", ROOT / "server" / "solar_geo_formats.py")
probes = _load("solar_geo_formats_probes", ROOT / "scripts" / "solar_geo_formats_probes.py")

REFERENCE_DIR = ROOT / "docs/parity/evidence/probes/demo-probes-20260923"
ALL_FILES = tuple(name for demo in sorted(probes.DEMOS) for name in probes.file_names(demo))
BOM = b"\xef\xbb\xbf"
# The commands that pass Encoding.UTF8 to File.WriteAllText.
FILES_WITH_BOM = frozenset({"leafkmlimport_demo.csv", "leaflandxml_fixed.xml",
                            "leaflandxml_delaunay.xml"})
# XmlWriter writes no newline after the root's end tag; AppendLine always does.
FILES_WITHOUT_FINAL_NEWLINE = frozenset(
    name for name in ALL_FILES if name.endswith(".kml") or name.startswith("leafkmlexportfmt_demo_F"))
# The file LEAFKMLIMPORTDEMO read on the licensed host; it appears only in the
# report's `#` line.
LICENSED_KML_PATH = r"C:\Users\User\AppData\Local\Temp\leafkmlexport_demo.kml"
CSV_FILES = ("leafkmlexportfmt_demo.csv", "leafkmlimport_demo.csv", "leafimportlandxml_demo.csv")


@functools.lru_cache(maxsize=None)
def generated_bytes(name):
    """Studio's own bytes for one file, computed from its fixture (once per run)."""
    demo = probes.FILE_DEMOS[name]
    if demo == "leafkmlimport":
        files = probes.build_kml_import(kml_path=LICENSED_KML_PATH)
    else:
        files = probes.build(demo)
    return probes.file_bytes(name, files[name])


def reference_bytes(name):
    return (REFERENCE_DIR / name).read_bytes()


def lf(data):
    return data.replace(b"\r\n", b"\n")


def data_rows(data):
    """(header cells, [row cells]) of one probe CSV: BOM and `#` preamble skipped."""
    text = data.decode("utf-8")
    if text.startswith("\ufeff"):
        text = text[1:]
    lines = [line for line in text.replace("\r\n", "\n").split("\n") if line]
    while lines and lines[0].startswith("#"):
        lines.pop(0)
    return lines[0].split(","), [line.split(",") for line in lines[1:]]


def _licensed_row_cases():
    cases = []
    for name in CSV_FILES:
        _, rows = data_rows(reference_bytes(name))
        cases.extend((name, index) for index in range(len(rows)))
    return cases


# --------------------------------------------------------------------------- #
# Layer 1: the licensed captures, reproduced by computing them
# --------------------------------------------------------------------------- #
def test_every_licensed_file_is_committed():
    """A subset check: this slice's own eighteen files, never the folder's list."""
    assert len(ALL_FILES) == 18
    for name in ALL_FILES:
        assert (REFERENCE_DIR / name).is_file(), name


@pytest.mark.parametrize("name", ALL_FILES)
def test_licensed_file_is_reproduced_by_computing_it(name):
    assert lf(generated_bytes(name)) == lf(reference_bytes(name))


@pytest.mark.parametrize("name", ALL_FILES)
def test_generated_bytes_carry_the_plugins_encoding_and_crlf(name):
    data = generated_bytes(name)
    assert data.startswith(BOM) == (name in FILES_WITH_BOM)
    assert b"\n" in data
    assert data.count(b"\n") == data.count(b"\r\n")
    assert data.endswith(b"\r\n") == (name not in FILES_WITHOUT_FINAL_NEWLINE)
    data.decode("utf-8")


@pytest.mark.parametrize("name,index", _licensed_row_cases())
def test_licensed_csv_row_is_reproduced(name, index):
    reference_header, reference_rows = data_rows(reference_bytes(name))
    header, rows = data_rows(generated_bytes(name))
    assert header == reference_header
    assert len(rows) == len(reference_rows)
    assert rows[index] == reference_rows[index]


def test_import_report_rows_do_not_depend_on_the_path_read():
    """The `#` line names the file read; the rows are the parser's output alone."""
    own = probes.build_kml_import()["leafkmlimport_demo.csv"]
    assert own.startswith("\ufeff# LEAFKMLIMPORTDEMO round-trip re-parse of leafkmlexport_demo.kml\r\n")
    assert data_rows(own.encode("utf-8")) == data_rows(reference_bytes("leafkmlimport_demo.csv"))


def test_delaunay_equals_fixed_on_the_uniform_grid():
    """The cocircular fallback: every grid cell is a rectangle, so no diagonal swaps."""
    assert generated_bytes("leaflandxml_delaunay.xml") == generated_bytes("leaflandxml_fixed.xml")


def test_landxml_has_441_points_and_800_faces():
    root = engine.parse_xml(generated_bytes("leaflandxml_fixed.xml").decode("utf-8"))
    assert engine.count_local_names(root, "P") == 441
    assert engine.count_local_names(root, "F") == 800


# --------------------------------------------------------------------------- #
# Layer 2: KML writer branches (KmlBoundaryExporter.cs)
# --------------------------------------------------------------------------- #
C = engine.KmlCoordinate
PP = engine.KmlProjectedPoint


def coordinates_of(kml):
    start = kml.index("<coordinates>") + len("<coordinates>")
    return kml[start:kml.index("</coordinates>")]


def triangle(alts=(0.0, 0.0, 0.0)):
    return [C(10.0, 40.0, alts[0]), C(11.0, 40.0, alts[1]), C(10.0, 41.0, alts[2])]


def test_zero_altitude_is_omitted_and_the_ring_is_closed():
    kml = engine.write_kml([engine.KmlPolygon("p", triangle())], "d")
    assert coordinates_of(kml) == "10,40 11,40 10,41 10,40"


def test_nonzero_altitude_is_a_three_tuple_per_vertex():
    kml = engine.write_kml([engine.KmlPolygon("p", triangle((0.0, 50.0, 0.0)))], "d")
    assert coordinates_of(kml) == "10,40 11,40,50 10,41 10,40"


def test_an_explicitly_closed_ring_is_not_closed_twice():
    kml = engine.write_kml([engine.KmlPolygon("p", triangle() + [C(10.0, 40.0)])], "d")
    assert coordinates_of(kml) == "10,40 11,40 10,41 10,40"


def test_closure_epsilon_is_strict_1e_12_on_altitude_too():
    closed = engine.write_kml([engine.KmlPolygon("p", triangle() + [C(10.0, 40.0, 1e-15)])], "d")
    assert coordinates_of(closed) == "10,40 11,40 10,41 10,40"
    opened = engine.write_kml([engine.KmlPolygon("p", triangle() + [C(10.0, 40.0, 1e-11)])], "d")
    # G17 of the double nearest 1e-11 is its exact 17-digit value, as C# prints it.
    assert coordinates_of(opened) == "10,40 11,40 10,41 10,40,9.9999999999999994E-12 10,40"


def test_missing_names_and_null_polygons_are_omitted():
    kml = engine.write_kml([None, engine.KmlPolygon(None, triangle()),
                            engine.KmlPolygon("", triangle())], None)
    assert "<name>" not in kml
    assert kml.count("<Placemark>") == 2


def test_an_empty_document_is_written_as_an_empty_element():
    assert engine.write_kml([], "") == (
        '<?xml version="1.0" encoding="utf-8"?>\r\n'
        '<kml xmlns="http://www.opengis.net/kml/2.2">\r\n'
        "  <Document />\r\n"
        "</kml>")


def test_a_polygon_with_no_vertices_writes_empty_coordinates():
    kml = engine.write_kml([engine.KmlPolygon("p", None)], "d")
    assert "<coordinates></coordinates>" in kml


def test_write_kml_refuses_a_null_polygon_list():
    with pytest.raises(TypeError):
        engine.write_kml(None, "d")


@pytest.mark.parametrize("value,text", [
    (-123.45678901234567, "-123.45678901234567"),
    (40.0, "40"),
    (0.1, "0.10000000000000001"),
    (1e-5, "1.0000000000000001E-05"),
    (-0.0, "-0"),
    (1e20, "1E+20"),
])
def test_g17_renders_like_csharp(value, text):
    assert engine.format_g17(value) == text
    assert float(text) == value


def test_text_is_escaped_and_newlines_become_crlf():
    kml = engine.write_kml([engine.KmlPolygon("A & B <c>\nd", triangle())], "x>y")
    assert "<name>x&gt;y</name>" in kml
    assert "<name>A &amp; B &lt;c&gt;\r\nd</name>" in kml


@pytest.mark.parametrize("bad", ["a\x01b", "a\ufffeb", "a\ud800b"])
def test_characters_xml_cannot_carry_are_refused(bad):
    with pytest.raises(engine.GeoFormatError):
        engine.write_kml([engine.KmlPolygon(bad, triangle())], "d")


def test_the_pole_guard_carries_the_licensed_message():
    with pytest.raises(engine.KmlArgumentError) as caught:
        engine.write_kml_from_projected([("p", [PP(0.0, 0.0)])], 90.0, 0.0, "d")
    assert str(caught.value) == engine.POLE_GUARD_MESSAGE
    assert isinstance(caught.value, ValueError)


def test_projected_export_inverts_the_parsers_projection():
    kml = engine.write_kml_from_projected(
        [("p", [PP(0.0, 0.0), PP(200.0, 0.0), PP(0.0, 100.0)])], 40.0, -105.0, "d")
    polygon = engine.parse_kml(kml)[0]
    projected = engine.project_equirectangular(polygon, C(-105.0, 40.0))
    assert [(round(p.x, 6), round(p.y, 6)) for p in projected] == [
        (0.0, 0.0), (200.0, 0.0), (0.0, 100.0)]


# --------------------------------------------------------------------------- #
# Layer 2: KML reader branches (KmlBoundaryParser.cs)
# --------------------------------------------------------------------------- #
def placemark(body, name="<name> P </name>"):
    return ("<kml><Document><Placemark>%s%s</Placemark></Document></kml>" % (name, body))


RING = ("<Polygon><outerBoundaryIs><LinearRing><coordinates>%s</coordinates>"
        "</LinearRing></outerBoundaryIs></Polygon>")


def test_the_licensed_export_parses_back_to_three_four_vertex_polygons():
    polygons = engine.parse_kml(reference_bytes("leafkmlexport_demo.kml").decode("utf-8"))
    assert [p.name for p in polygons] == ["Site Boundary", "Tracker Row 1", "Tracker Row 2"]
    assert [len(p.vertices) for p in polygons] == [4, 4, 4]
    centers = [engine.centroid(p) for p in polygons]
    for center, (lon, lat) in zip(centers, [(-105.0, 40.0), (-105.0, 40.00018),
                                            (-105.0, 39.99982)]):
        assert abs(center.lon_deg - lon) < 1e-5 and abs(center.lat_deg - lat) < 1e-5


def test_the_name_is_trimmed_and_a_bare_namespace_is_accepted():
    polygons = engine.parse_kml(placemark(RING % "1,2 3,2 3,4 1,2"))
    assert polygons[0].name == "P"
    assert [(v.lon_deg, v.lat_deg) for v in polygons[0].vertices] == [(1, 2), (3, 2), (3, 4)]


def test_a_prefixed_namespace_is_matched_by_local_name():
    kml = ('<k:kml xmlns:k="http://www.opengis.net/kml/2.2"><k:Placemark>'
           "<k:Polygon><k:outerBoundaryIs><k:LinearRing><k:coordinates>1,2 3,2 3,4"
           "</k:coordinates></k:LinearRing></k:outerBoundaryIs></k:Polygon>"
           "</k:Placemark></k:kml>")
    assert len(engine.parse_kml(kml)) == 1


def test_point_placemarks_and_degenerate_rings_are_skipped():
    point = placemark("<Point><coordinates>1,2</coordinates></Point>")
    assert engine.parse_kml(point) == []
    degenerate = placemark(RING % "1,2 3,2 1,2")
    assert engine.parse_kml(degenerate) == []


def test_a_placemark_without_a_name_reads_as_empty():
    polygons = engine.parse_kml(placemark(RING % "1,2 3,2 3,4", name=""))
    assert polygons[0].name == ""


def test_the_altitude_is_read_when_present():
    polygons = engine.parse_kml(placemark(RING % "1,2,7 3,2,8\n\t3,4,9"))
    assert [v.altitude_m for v in polygons[0].vertices] == [7.0, 8.0, 9.0]


@pytest.mark.parametrize("coordinates", ["1,2 3 3,4", "1,2 x,2 3,4", "1,2 1_0,2 3,4"])
def test_a_malformed_coordinate_is_a_format_error(coordinates):
    with pytest.raises(engine.GeoFormatError):
        engine.parse_kml(placemark(RING % coordinates))


def test_parse_kml_refuses_none():
    with pytest.raises(TypeError):
        engine.parse_kml(None)


def test_centroid_refuses_an_empty_polygon():
    with pytest.raises(ValueError):
        engine.centroid(engine.KmlPolygon("p", []))


# --------------------------------------------------------------------------- #
# Layer 2: LandXML writer (TerrainExporter.cs)
# --------------------------------------------------------------------------- #
STAMP = datetime(2026, 9, 23, 5, 41, 53)


def small_grid():
    return engine.TerrainGridInterpolator([1.0, 2.0, 3.0, 4.0], 2, 2, 0.0, 10.0, 0.0, 20.0)


def test_points_are_north_east_z_scaled_and_z_is_not_scaled():
    xml = engine.to_landxml(small_grid(), "S", 0.5, engine.TRIANGULATION_FIXED, STAMP)
    assert '          <P id="2">0.000 5.000 2.000</P>\r\n' in xml
    assert '          <P id="3">10.000 0.000 3.000</P>\r\n' in xml
    assert "          <F>1 2 4</F>\r\n          <F>1 4 3</F>\r\n" in xml


def test_the_clock_is_rendered_in_utc():
    local = datetime(2026, 9, 23, 0, 41, 53, tzinfo=timezone(timedelta(hours=-5)))
    xml = engine.to_landxml(small_grid(), "S", 1.0, engine.TRIANGULATION_FIXED, local)
    assert '         date="2026-09-23" time="05:41:53">\r\n' in xml


def test_the_in_circle_test_swaps_only_when_the_fourth_corner_is_inside():
    assert engine.pick_bl_tr_diagonal(0, 0, 2, 0, 2, 1, 0, 5) is True
    assert engine.pick_bl_tr_diagonal(0, 0, 1, 0, 1, 1, 0.2, 0.9) is False
    assert engine.pick_bl_tr_diagonal(0, 0, 1, 0, 1, 1, 0, 1) is True


@pytest.mark.parametrize("arguments,error", [
    ((None, "S", 1.0, "Fixed", STAMP), TypeError),
    (("grid", "S", 0.0, "Fixed", STAMP), ValueError),
    (("grid", "S", 1.0, "Sideways", STAMP), ValueError),
    (("grid", 'a"b', 1.0, "Fixed", STAMP), engine.GeoFormatError),
    (("grid", "a<b", 1.0, "Fixed", STAMP), engine.GeoFormatError),
    (("grid", "S", 1.0, "Fixed", "2026-09-23"), TypeError),
])
def test_to_landxml_fails_closed(arguments, error):
    arguments = tuple(small_grid() if value == "grid" else value for value in arguments)
    with pytest.raises(error):
        engine.to_landxml(*arguments)


def test_a_grid_with_one_row_cannot_be_triangulated():
    grid = engine.TerrainGridInterpolator([1.0, 2.0], 1, 2, 0.0, 1.0, 0.0, 1.0)
    with pytest.raises(ValueError):
        engine.to_landxml(grid, "S", 1.0, engine.TRIANGULATION_FIXED, STAMP)


# --------------------------------------------------------------------------- #
# Layer 2: LandXML reader (TerrainImporter.cs, LandXmlImporter.cs)
# --------------------------------------------------------------------------- #
def fixture_points(fixture_id):
    return engine.parse_landxml_points(dict(probes.LANDXML_IMPORT_FIXTURES)[fixture_id])


def test_the_default_namespace_is_stripped():
    assert fixture_points("F1_BASIC_NO_NS") == fixture_points("F2_WITH_NAMESPACE")
    assert fixture_points("F1_BASIC_NO_NS")[1] == engine.SurveyPoint(0.0, 10.0, 101.0)


def test_malformed_points_are_skipped_silently():
    assert fixture_points("F3_BAD_LINES") == [engine.SurveyPoint(1.0, 2.0, 50.0),
                                              engine.SurveyPoint(4.0, 5.0, 60.0)]


@pytest.mark.parametrize("token", ["NaN", "Infinity", "-Infinity", "1e999", "1_0", "0x10"])
def test_non_finite_and_non_decimal_tokens_are_skipped(token):
    xml = "<LandXML><P>1 2 3</P><P>%s 2 3</P><P>4 5 6 7</P></LandXML>" % token
    assert engine.parse_landxml_points(xml) == [engine.SurveyPoint(2.0, 1.0, 3.0),
                                                engine.SurveyPoint(5.0, 4.0, 6.0)]


def test_a_p_root_and_mixed_whitespace_are_read():
    assert engine.parse_landxml_points("<P>\u00a01\t2\n3 </P>") == [engine.SurveyPoint(2, 1, 3)]


def test_parse_points_swaps_for_easting_first_files():
    xml = "<LandXML><P>1 2 3</P></LandXML>"
    assert engine.parse_points(xml)[0] == engine.SurveyPoint(2.0, 1.0, 3.0)
    assert engine.parse_points(xml, northing_is_y=False)[0] == engine.SurveyPoint(1.0, 2.0, 3.0)


def test_resample_returns_source_elevation_on_coincidence_and_follows_aspect():
    points = [engine.SurveyPoint(0, 0, 1), engine.SurveyPoint(20, 0, 2),
              engine.SurveyPoint(0, 10, 3), engine.SurveyPoint(20, 10, 4)]
    grid = engine.resample_to_grid(points, 4)
    assert (grid.cols, grid.rows) == (4, 2)
    assert grid.elevations[0] == 1.0 and grid.elevations[-1] == 4.0
    assert grid.source_points == 4
    assert 1.0 < grid.elevations[1] < 4.0


@pytest.mark.parametrize("points,cells", [
    ([engine.SurveyPoint(0, 0, 1), engine.SurveyPoint(1, 1, 1)], 4),
    ([engine.SurveyPoint(0, 0, 1), engine.SurveyPoint(1, 1, 1), engine.SurveyPoint(2, 0, 1)], 1),
])
def test_resample_refuses_too_few_points_or_cells(points, cells):
    with pytest.raises(ValueError):
        engine.resample_to_grid(points, cells)


def test_resample_all_coincident_points_use_a_one_metre_span():
    points = [engine.SurveyPoint(5, 5, 2)] * 3
    grid = engine.resample_to_grid(points, 3)
    assert (grid.x_min, grid.x_max, grid.y_min, grid.y_max) == (5, 6, 5, 6)
    assert set(grid.elevations) == {2.0}


# --------------------------------------------------------------------------- #
# Layer 3: hostile XML, refused at every entry point
# --------------------------------------------------------------------------- #
BILLION_LAUGHS = ('<?xml version="1.0"?><!DOCTYPE kml [<!ENTITY a "aaaaaaaaaa">'
                  '<!ENTITY b "&a;&a;&a;&a;&a;&a;&a;&a;&a;&a;">'
                  '<!ENTITY c "&b;&b;&b;&b;&b;&b;&b;&b;&b;&b;">]><kml><name>&c;</name></kml>')
EXTERNAL_ENTITY = ('<?xml version="1.0"?><!DOCTYPE kml [<!ENTITY x SYSTEM "file:///etc/passwd">]>'
                   "<kml><name>&x;</name></kml>")
PARAMETER_ENTITY = ('<?xml version="1.0"?><!DOCTYPE kml [<!ENTITY % p SYSTEM '
                    '"http://example.invalid/p.dtd"> %p;]><kml/>')
EXTERNAL_DTD = '<?xml version="1.0"?><!DOCTYPE kml SYSTEM "http://example.invalid/k.dtd"><kml/>'
HOSTILE = {"billion-laughs": BILLION_LAUGHS, "external-entity": EXTERNAL_ENTITY,
           "parameter-entity": PARAMETER_ENTITY, "external-dtd": EXTERNAL_DTD}
MALFORMED = {"undefined-entity": "<kml><name>&x;</name></kml>",
             "unbound-prefix": "<k:kml/>",
             "unclosed": "<kml><Document></kml>",
             "empty": "",
             "two-roots": "<kml/><kml/>"}
ENTRY_POINTS = {"parse_xml": engine.parse_xml, "parse_kml": engine.parse_kml,
                "parse_landxml_points": engine.parse_landxml_points}


@pytest.mark.parametrize("entry", sorted(ENTRY_POINTS))
@pytest.mark.parametrize("case", sorted(HOSTILE))
def test_a_dtd_or_entity_is_refused_before_expansion(entry, case):
    with pytest.raises(engine.UnsafeXmlError):
        ENTRY_POINTS[entry](HOSTILE[case])


@pytest.mark.parametrize("case", sorted(MALFORMED))
def test_malformed_xml_is_a_format_error(case):
    with pytest.raises(engine.GeoFormatError):
        engine.parse_xml(MALFORMED[case])


def test_depth_is_bounded_without_touching_the_python_stack():
    depth = engine.MAX_XML_DEPTH + 1
    with pytest.raises(engine.UnsafeXmlError):
        engine.parse_xml("<a>" * depth + "</a>" * depth)
    ok = engine.MAX_XML_DEPTH
    root = engine.parse_xml("<a>" * ok + "x" + "</a>" * ok)
    assert root.value() == "x" and len(root.descendants()) == ok - 1


def test_size_is_bounded_before_parsing():
    with pytest.raises(engine.UnsafeXmlError):
        engine.parse_xml("<kml>" + " " * engine.MAX_XML_CHARS + "</kml>")


def test_parse_xml_refuses_bytes():
    with pytest.raises(TypeError):
        engine.parse_xml(b"<kml/>")


def test_a_leading_byte_order_mark_is_encoding():
    assert engine.parse_xml("\ufeff<kml/>").local_name == "kml"


# --------------------------------------------------------------------------- #
# The probe writer
# --------------------------------------------------------------------------- #
def test_all_writes_every_file_and_the_import_reads_studios_own_kml(tmp_path):
    assert probes.main(["--out-dir", str(tmp_path), "--all"]) == 0
    assert sorted(path.name for path in tmp_path.iterdir()) == sorted(ALL_FILES)
    report = (tmp_path / "leafkmlimport_demo.csv").read_bytes().decode("utf-8")
    assert report.startswith("\ufeff# LEAFKMLIMPORTDEMO round-trip re-parse of "
                             + str(tmp_path / "leafkmlexport_demo.kml") + "\r\n")
    for name in ALL_FILES:
        if name != "leafkmlimport_demo.csv":
            assert (tmp_path / name).read_bytes() == generated_bytes(name), name


def test_the_writer_needs_a_demo(tmp_path):
    assert probes.main(["--out-dir", str(tmp_path)]) == 2


def test_build_refuses_an_unknown_demo():
    with pytest.raises(ValueError):
        probes.build("leafnope")
    with pytest.raises(ValueError):
        probes.file_names("leafnope")
    with pytest.raises(ValueError):
        probes.file_bytes("nope.csv", "")


def test_the_landxml_clock_is_an_input():
    later = probes.build_landxml(datetime(2030, 1, 2, 3, 4, 5))
    assert 'date="2030-01-02" time="03:04:05"' in later["leaflandxml_fixed.xml"]
    assert not math.isnan(probes.landxml_interpolator().elevations[0])
