"""Studio's harness planner and tracker BOM against the licensed plugin, computed.

Three layers, all hermetic and none of them skipping:

  1. The plugin's OWN unit tests, ported case for case from
     Tests/Tests/LeafHarnessCalculatorTests.cs, Tests/Tests/LeafBomTests.cs,
     Tests/Tests/LeafBomXlsxTests.cs and Tests/Tests/LeafBomXlsxHarnessTests.cs
     (read 2026-09-22 at C:/tmp/solar-parity/wt-b25-s17). The two
     `GetActiveModule` cases are omitted: they read AutoCAD drawing properties,
     which is not what this port covers, and the omission is named here rather
     than left as a silent gap.
  2. Every probe in the four licensed DEMO captures, reproduced by RUNNING
     Studio's fixtures through server/solar_harness_bom.py. The captures are the
     licensed AutoCAD 2025 run of 2026-09-23 and are COMMITTED at
     docs/parity/evidence/probes/demo-probes-20260923, so this layer reads the
     artifact itself rather than a transcription and every runner carries it.
     Each file is asserted whole and then probe by probe, so a failure names the
     scenario or the sheet row that moved.
  3. The branches the EMPTY demo exists to pin: Cable Tray null versus empty,
     the Electrical and Piling placeholders, and the By Area first-occurrence
     grouping.

Line endings, and why the whole-file assertion normalizes them. The plugin
writes CRLF and this port writes CRLF, which `test_the_generated_csv_uses_the
_plugins_crlf_and_ascii` asserts on the GENERATED bytes. The committed capture
is a tracked text file, so git's checkout translation decides its on-disk line
endings, and comparing against it byte for byte would be asserting a git setting
rather than a parity fact. The workbooks are binary to git and are compared as
cell values, which is what rule E5 compares.

Nothing here feeds a captured value back into the port: solar_harness_bom.py
computes every number and renders every string, and these are the assertions it
must meet.
"""

from __future__ import annotations

import importlib.util
import math
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[2]


def _load(name, path):
    spec = importlib.util.spec_from_file_location(name, path)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


engine = _load("solar_harness_bom", ROOT / "server" / "solar_harness_bom.py")
xlsx = _load("solar_xlsx", ROOT / "server" / "solar_xlsx.py")
probes = _load("solar_harness_bom_probes", ROOT / "scripts" / "solar_harness_bom_probes.py")

# The licensed capture is committed in this repo, so every runner carries it.
REFERENCE_DIR = ROOT / "docs/parity/evidence/probes/demo-probes-20260923"
ALL_FILES = tuple(name for demo in sorted(probes.DEMOS)
                  for name in probes.file_names(demo))
WORKBOOK_FILES = tuple(name for name in ALL_FILES if name.endswith(".xlsx"))
CSV_FILE = "leafharnessplan_demo.csv"
PITCH = 1.134     # the pitch every ported NUnit fixture uses


def generated(name):
    """Studio's own content for one file, computed from its fixture."""
    return probes.build(probes.FILE_DEMOS[name])[name]


def reference_workbook(name):
    return xlsx.read_workbook_file(REFERENCE_DIR / name)


def generated_workbook(name):
    """Studio's workbook through its own writer and reader, so both sides are
    compared as the cell values rule E5 names, never as storage bytes."""
    return xlsx.read_workbook(xlsx.write_workbook(generated(name)))


def rows_of(sheets, name):
    for sheet in sheets:
        if sheet.name == name:
            return {row.index: row.cells for row in sheet.rows}
    raise AssertionError("workbook has no sheet " + name)


def csv_rows(text):
    """The capture's data rows as dicts, keyed by the pipe-separated header."""
    lines = [line for line in text.replace("\r\n", "\n").split("\n") if line]
    header = lines[0].split("|")
    return {cells[0]: dict(zip(header, cells))
            for cells in (line.split("|") for line in lines[1:])}


def ten_module_tracker_end_of_row():
    """LeafHarnessCalculatorTests.TenModuleTrackerEndOfRow (cs:24-33)."""
    return engine.HarnessStringInput(
        module_count=10, module_pitch_m=PITCH, trunk_tap_from_start_m=0.0,
        string_max_amps=18.0, is_tracker_row=True, requested_type=engine.END_OF_ROW)


def default_module():
    """LeafBomTests.DefaultModule (cs:20-28): PmaxW defaults to 0."""
    return engine.TrackerModuleSpec(along_axis_m=1.000, cross_axis_m=2.100, gap_m=0.020)


def module_with_550w():
    """LeafBomTests.ModuleWith550W (cs:376-385)."""
    return engine.TrackerModuleSpec(along_axis_m=1.000, cross_axis_m=2.100,
                                    gap_m=0.020, pmax_w=550.0)


def make_row(slots, physical_length_m, row_index=0):
    """LeafBomTests.MakeRow (cs:31-40): overhang 0, so physical == length."""
    return engine.TrackerRow(axis_start=(0, 0), axis_end=(0, physical_length_m),
                             module_slots=slots, length_meters=physical_length_m,
                             rail_overhang_m=0.0, row_index=row_index)


# --------------------------------------------------------------------------- #
# Layer 1a: LeafHarnessCalculatorTests.cs
# --------------------------------------------------------------------------- #
def test_plan_null_input_throws():
    with pytest.raises(engine.HarnessArgumentError):
        engine.plan(None)


@pytest.mark.parametrize("attribute,value", [
    ("module_count", 0), ("module_pitch_m", -1.0), ("string_max_amps", -5.0),
])
def test_plan_refuses_an_out_of_range_input(attribute, value):
    spec = ten_module_tracker_end_of_row()
    setattr(spec, attribute, value)
    with pytest.raises(engine.HarnessArgumentError):
        engine.plan(spec)


def test_acceptance_q27a_ten_module_end_harness_connectors_and_drops():
    plan = engine.plan(ten_module_tracker_end_of_row())
    assert plan.type == engine.END_OF_ROW
    assert plan.connectors == 10
    assert len(plan.module_drop_lengths_m) == 10
    for index in range(10):
        assert plan.module_drop_lengths_m[index] == pytest.approx(index * PITCH, abs=1e-9)
    assert plan.total_cable_length_m == pytest.approx(45 * PITCH, abs=1e-9)


def test_end_harness_tap_at_middle_drops_are_symmetric():
    spec = ten_module_tracker_end_of_row()
    spec.trunk_tap_from_start_m = 5 * PITCH
    plan = engine.plan(spec)
    expected = (5, 4, 3, 2, 1, 0, 1, 2, 3, 4)
    for index, multiple in enumerate(expected):
        assert plan.module_drop_lengths_m[index] == pytest.approx(multiple * PITCH, abs=1e-9)


@pytest.mark.parametrize("amps,awg", [(15.0, 10), (40.0, 8), (70.0, 6)])
def test_gauge_selection_follows_the_ampacity_ladder(amps, awg):
    spec = ten_module_tracker_end_of_row()
    spec.string_max_amps = amps
    assert engine.plan(spec).cable_gauge_awg == awg


def test_gauge_selection_beyond_the_ladder_throws():
    spec = ten_module_tracker_end_of_row()
    spec.string_max_amps = 400.0
    with pytest.raises(engine.HarnessSupportError):
        engine.plan(spec)


def test_acceptance_q27a_parallel_on_fixed_tilt_throws():
    spec = ten_module_tracker_end_of_row()
    spec.is_tracker_row = False
    spec.requested_type = engine.PARALLEL_TRUNK
    with pytest.raises(engine.HarnessSupportError) as error:
        engine.plan(spec)
    assert "Parallel" in str(error.value)


def test_motor_on_fixed_tilt_throws():
    spec = ten_module_tracker_end_of_row()
    spec.is_tracker_row = False
    spec.requested_type = engine.MOTOR
    with pytest.raises(engine.HarnessSupportError):
        engine.plan(spec)


def test_motor_harness_tracker_returns_a_single_connector():
    spec = ten_module_tracker_end_of_row()
    spec.requested_type = engine.MOTOR
    spec.trunk_tap_from_start_m = 5.0
    plan = engine.plan(spec)
    assert plan.type == engine.MOTOR
    assert plan.connectors == 1
    assert len(plan.module_drop_lengths_m) == 1
    mid_row_m = (10 - 1) * 0.5 * PITCH
    assert plan.module_drop_lengths_m[0] == pytest.approx(abs(mid_row_m - 5.0), abs=1e-9)


def test_parallel_trunk_tracker_connectors_equal_module_count():
    spec = ten_module_tracker_end_of_row()
    spec.requested_type = engine.PARALLEL_TRUNK
    spec.trunk_tap_from_start_m = 2 * PITCH
    plan = engine.plan(spec)
    assert plan.type == engine.PARALLEL_TRUNK
    assert plan.connectors == 10
    assert all(drop >= 0 for drop in plan.module_drop_lengths_m)
    assert plan.module_drop_lengths_m[2] == pytest.approx(0.0, abs=1e-9)


@pytest.mark.parametrize("amps,awg", [
    (0.0, 10), (30.0, 10), (30.001, 8), (55.0, 8), (55.001, 6),
    (75.0, 6), (75.001, 4), (95.0, 4), (95.001, 2), (130.0, 2),
])
def test_the_ladder_steps_on_the_boundary_not_past_it(amps, awg):
    """Every ceiling is INCLUSIVE, which is what the S0..S9 sweep exists to pin."""
    assert engine.select_gauge(amps) == awg


def test_over_ladder_current_names_the_ceiling_it_exceeded():
    with pytest.raises(engine.HarnessSupportError) as error:
        engine.select_gauge(150.0)
    assert str(error.value) == (
        "String current 150.0 A exceeds the largest supported PV-wire gauge in "
        "the ampacity ladder (130 A). Split the string or use a combiner.")


# --------------------------------------------------------------------------- #
# Layer 1b: LeafBomTests.cs
# --------------------------------------------------------------------------- #
def test_compute_null_rows_throws():
    with pytest.raises(engine.BomArgumentError):
        engine.compute_bom(None, default_module())


def test_compute_null_module_throws():
    with pytest.raises(engine.BomArgumentError):
        engine.compute_bom([], None)


@pytest.mark.parametrize("spacing", [0.0, -1.0])
def test_compute_non_positive_pile_spacing_throws(spacing):
    with pytest.raises(engine.BomArgumentError):
        engine.compute_bom([], default_module(), spacing)


def test_compute_empty_rows_is_all_zeros():
    result = engine.compute_bom([], default_module())
    assert (result.total_rows, result.total_modules, result.total_piles) == (0, 0, 0)
    assert result.total_tube_length_m == pytest.approx(0.0, abs=1e-9)


def test_compute_single_row_totals():
    result = engine.compute_bom([make_row(10, 10.2)], default_module())
    assert result.total_rows == 1
    assert result.total_drive_units == 1
    assert engine.compute_bom([make_row(22, 22.5)], default_module()).total_modules == 22
    assert engine.compute_bom([make_row(10, 10.3)], default_module()) \
        .total_tube_length_m == pytest.approx(10.3, abs=1e-9)


def test_compute_short_row_still_gets_a_pile():
    assert engine.compute_bom([make_row(1, 2.0)], default_module(), 5.0).total_piles >= 1


def test_compute_long_row_pile_count_is_the_ceiling():
    assert engine.compute_bom([make_row(10, 10.0)], default_module(), 5.0).total_piles == 2


def test_compute_multiple_rows_piles_are_summed_per_row():
    rows = [make_row(10, 10.0, 0), make_row(3, 3.0, 1)]
    assert engine.compute_bom(rows, default_module(), 5.0).total_piles == 3


def test_compute_row_pile_count_override_uses_the_drawing_count():
    rows = [make_row(108, 131.0, 0), make_row(84, 102.0, 1)]
    rows[0].pile_count_override = 2
    rows[1].pile_count_override = 2
    assert engine.compute_bom(rows, default_module(), 5.0).total_piles == 4


def test_a_mixed_pile_source_names_both_in_the_description():
    """The third pile description exists only when BOTH counting paths ran."""
    rows = [make_row(10, 10.0, 0), make_row(10, 10.0, 1)]
    rows[0].pile_count_override = 7
    result = engine.compute_bom(rows, default_module(), 5.0)
    pile = next(line for line in result.lines if line.category == "Pile")
    assert pile.description == ("Ground pile / foundation (drawing XData where "
                                "present; otherwise 5.0 m c/c estimated)")
    assert result.total_piles == 9


def test_an_explicit_only_pile_source_names_the_xdata():
    rows = [make_row(10, 10.0, 0)]
    rows[0].pile_count_override = 7
    result = engine.compute_bom(rows, default_module(), 5.0)
    pile = next(line for line in result.lines if line.category == "Pile")
    assert pile.description == "Ground pile / foundation (from drawing XData)"


def test_a_row_excluded_from_estimation_still_counts_everywhere_else():
    rows = [make_row(10, 10.0, 0)]
    rows[0].no_piles_estimated = True
    result = engine.compute_bom(rows, default_module(), 5.0)
    assert result.total_piles == 0
    assert (result.total_rows, result.total_modules, result.total_drive_units) == (1, 10, 1)


def test_compute_multiple_rows_aggregates():
    rows = [make_row(20, 20.4, 0), make_row(15, 15.3, 1)]
    result = engine.compute_bom(rows, default_module())
    assert result.total_modules == 35
    assert result.total_tube_length_m == pytest.approx(35.7, abs=1e-9)
    assert result.total_drive_units == 2


@pytest.mark.parametrize("category", ["Module", "Torque Tube", "Pile", "Drive Unit"])
def test_compute_with_rows_emits_each_category(category):
    result = engine.compute_bom([make_row(10, 10.0)], default_module())
    assert any(line.category == category for line in result.lines)


def test_module_line_quantity_matches_total_modules():
    result = engine.compute_bom([make_row(20, 20.4)], default_module())
    module = next(line for line in result.lines if line.category == "Module")
    assert module.quantity == pytest.approx(20, abs=1e-9)


def test_to_csv_has_the_header_row_and_names_the_module():
    csv = engine.bom_to_csv(engine.compute_bom([make_row(10, 10.0)], default_module()))
    assert csv.split("\r\n")[0] == "Category,Description,Unit,Quantity"
    assert "Module" in csv


def test_to_csv_on_empty_rows_is_header_plus_the_two_unconditional_lines():
    """Empty rows still emit Module, Pile and Drive Unit; only the tube pair is gated."""
    lines = [line for line in
             engine.bom_to_csv(engine.compute_bom([], default_module())).split("\r\n") if line]
    assert lines[0] == "Category,Description,Unit,Quantity"
    assert [line.split(",")[0] for line in lines[1:]] == ["Module", "Pile", "Drive Unit"]


def test_to_csv_quotes_a_description_holding_a_comma():
    """The torque tube description carries one, so the quoting rule is load-bearing."""
    csv = engine.bom_to_csv(engine.compute_bom([make_row(10, 10.0)], default_module()))
    assert '"Torque tube / tracker rail (1 sections, 10.0 m total)"' in csv


def test_default_pile_spacing_is_five():
    assert engine.DEFAULT_PILE_SPACING_M == 5.0


def test_physical_length_includes_overhang_at_both_ends():
    row = engine.TrackerRow(length_meters=10.0, rail_overhang_m=0.1)
    assert row.physical_length_meters == pytest.approx(10.2, abs=1e-9)


def test_compute_uses_physical_length_in_the_tube_total():
    row = engine.TrackerRow(axis_start=(0, 0), axis_end=(0, 10.2), module_slots=10,
                            length_meters=10.0, rail_overhang_m=0.1, row_index=0)
    result = engine.compute_bom([row], default_module())
    assert result.total_tube_length_m == pytest.approx(10.2, abs=1e-9)


def test_zero_pmax_means_no_dc_capacity_at_all():
    result = engine.compute_bom([make_row(10, 10.0)], default_module())
    assert result.total_dc_capacity_kwp == pytest.approx(0.0, abs=1e-9)
    assert not any(line.category == "DC Capacity" for line in result.lines)


def test_with_pmax_dc_capacity_is_modules_times_watts():
    result = engine.compute_bom([make_row(10, 10.2)], module_with_550w())
    assert result.total_dc_capacity_kwp == pytest.approx(5.5, abs=1e-9)
    dc_line = next(line for line in result.lines if line.category == "DC Capacity")
    assert dc_line.unit == "kWp"


def test_row_module_power_overrides_the_global_pmax():
    rows = [make_row(108, 131.0)]
    rows[0].module_power_watts = 535
    result = engine.compute_bom(rows, module_with_550w())
    assert result.total_dc_capacity_kwp == pytest.approx(57.78, abs=1e-9)


def test_with_pmax_multiple_rows_sums_modules():
    rows = [make_row(20, 20.4, 0), make_row(15, 15.3, 1)]
    result = engine.compute_bom(rows, module_with_550w())
    assert result.total_dc_capacity_kwp == pytest.approx(19.25, abs=1e-9)


def test_empty_rows_with_pmax_is_still_zero_capacity():
    assert engine.compute_bom([], module_with_550w()) \
        .total_dc_capacity_kwp == pytest.approx(0.0, abs=1e-9)


def test_module_spec_default_pmax_is_zero():
    assert engine.TrackerModuleSpec().pmax_w == 0.0


def test_a_row_only_pmax_names_the_xdata_in_the_dc_line():
    """The second DC description fires when the GLOBAL Pmax is zero but a row's is not."""
    rows = [make_row(10, 10.0)]
    rows[0].module_power_watts = 600
    result = engine.compute_bom(rows, default_module())
    dc_line = next(line for line in result.lines if line.category == "DC Capacity")
    assert dc_line.description == ("Total DC nameplate (10 modules; per-row Wp "
                                   "from drawing XData)")


# --------------------------------------------------------------------------- #
# Layer 1c: LeafBomXlsxTests.cs and LeafBomXlsxHarnessTests.cs
# --------------------------------------------------------------------------- #
def two_rows():
    """LeafBomXlsxTests.TwoRows (cs:35-48): 0.5 m overhang, so physical is 23.68."""
    return [engine.TrackerRow(row_index=0, module_slots=20, length_meters=22.68,
                              rail_overhang_m=0.5, axis_start=(0, 0), axis_end=(0, 22.68)),
            engine.TrackerRow(row_index=1, module_slots=20, length_meters=22.68,
                              rail_overhang_m=0.5, axis_start=(5, 0), axis_end=(5, 22.68))]


def sample_harnesses():
    """LeafBomXlsxHarnessTests.SampleHarnesses (cs:65-95): two End plus one Motor."""
    def one(harness_type):
        return engine.plan(engine.HarnessStringInput(
            module_count=10, module_pitch_m=PITCH, trunk_tap_from_start_m=0.0,
            string_max_amps=20.0, is_tracker_row=True, requested_type=harness_type))
    return [one(engine.END_OF_ROW), one(engine.END_OF_ROW), one(engine.MOTOR)]


def sample_workbook(harnesses=None, piles=True):
    rows = two_rows()
    bom = engine.compute_bom(rows, engine.TrackerModuleSpec(
        cross_axis_m=1.134, along_axis_m=2.384, pmax_w=610))
    coordinates = engine.generate_pile_coordinates(rows, 5.0) if piles else None
    return engine.build_bom_workbook(bom, rows, coordinates, harnesses)


def tab(workbook, name):
    return dict(next(rows for tab_name, rows in workbook if tab_name == name))


def test_acceptance_q24_workbook_contains_all_seven_spec_tabs():
    assert tuple(name for name, _ in sample_workbook()) == engine.TAB_NAMES


def test_overview_reports_aggregate_metrics():
    overview = tab(sample_workbook(), "Overview")
    assert overview[1] == ["Metric", "Value", "Unit"]
    assert overview[2][:2] == ["Total rows (sections)", 2]
    assert overview[3][:2] == ["Total modules", 40]


def test_layout_row_count_equals_the_input_rows():
    layout = tab(sample_workbook(), "Layout")
    assert layout[1] == list(engine.LAYOUT_HEADER)
    assert len(layout) == 3


def test_modules_tab_holds_only_the_module_lines():
    modules = tab(sample_workbook(), "Modules")
    assert len(modules) == 2
    assert modules[2][0] == "Module"


def test_electrical_shows_the_dc_capacity_line_when_pmax_is_given():
    electrical = tab(sample_workbook(), "Electrical")
    assert electrical[2][0] == "DC Capacity"


def test_acceptance_q25_piling_tab_has_a_row_per_pile():
    piling = tab(sample_workbook(), "Piling")
    assert piling[1] == list(engine.PILING_HEADER)
    piles = engine.generate_pile_coordinates(two_rows(), 5.0)
    assert len(piling) == len(piles) + 1


def test_generate_pile_coordinates_null_rows_throws():
    with pytest.raises(engine.BomArgumentError):
        engine.generate_pile_coordinates(None, 5.0)


@pytest.mark.parametrize("spacing", [0.0, -1.0])
def test_generate_pile_coordinates_non_positive_spacing_throws(spacing):
    with pytest.raises(engine.BomArgumentError):
        engine.generate_pile_coordinates([], spacing)


def test_generate_pile_coordinates_puts_piles_at_both_endpoints():
    rows = [engine.TrackerRow(row_index=0, module_slots=10, length_meters=10,
                              rail_overhang_m=0.0, axis_start=(0, 0), axis_end=(0, 10))]
    piles = engine.generate_pile_coordinates(rows, 5.0)
    assert len(piles) >= 2
    assert (piles[0].x, piles[0].y) == pytest.approx((0.0, 0.0), abs=1e-9)
    assert (piles[-1].x, piles[-1].y) == pytest.approx((0.0, 10.0), abs=1e-9)


def test_generate_pile_coordinates_samples_the_terrain_at_each_pile():
    """The plugin's case uses TerrainGridInterpolator, which this slice does not
    port; the sampling CONTRACT is what the exporter owns, so it is a double."""
    sampled = []

    class Terrain:
        def interpolate_z(self, x, y):
            sampled.append((x, y))
            return 150.0

    rows = [engine.TrackerRow(row_index=0, module_slots=10, length_meters=10,
                              rail_overhang_m=0.0, axis_start=(5, 0), axis_end=(5, 10))]
    piles = engine.generate_pile_coordinates(rows, 5.0, Terrain())
    assert all(pile.terrain_z == pytest.approx(150.0, abs=1e-6) for pile in piles)
    assert sampled == [(pile.x, pile.y) for pile in piles]


def test_a_degenerate_row_contributes_no_piles():
    rows = [engine.TrackerRow(row_index=0, module_slots=1, length_meters=1.0,
                              axis_start=(3, 4), axis_end=(3, 4))]
    assert engine.generate_pile_coordinates(rows, 5.0) == []


def test_acceptance_q26_cable_tray_has_extension_rows_by_length_and_type():
    tray = tab(sample_workbook(sample_harnesses()), "Cable Tray")
    assert tray[1] == list(engine.CABLE_TRAY_HEADER)
    # Two End harnesses share 10 distinct drops; the Motor's 4.5 x 1.134 =
    # 5.103 m is not a multiple of the pitch, so it is an eleventh bucket.
    assert len(tray) == 12


def test_cable_tray_identical_harnesses_group_with_count_two():
    tray = tab(sample_workbook(sample_harnesses()), "Cable Tray")
    data = [cells for index, cells in sorted(tray.items()) if index > 1]
    assert sum(1 for cells in data if cells[0] == "EndOfRow" and cells[3] == 2) == 10


def test_cable_tray_total_length_is_drop_times_count():
    tray = tab(sample_workbook(sample_harnesses()), "Cable Tray")
    for index, cells in sorted(tray.items()):
        if index == 1:
            continue
        assert cells[4] == pytest.approx(cells[2] * cells[3], abs=1e-9)


def test_cable_tray_aggregate_total_equals_the_sum_of_the_harness_totals():
    harnesses = sample_harnesses()
    tray = tab(sample_workbook(harnesses), "Cable Tray")
    total = sum(cells[4] for index, cells in tray.items() if index > 1)
    assert total == pytest.approx(sum(h.total_cable_length_m for h in harnesses), abs=1e-6)


def test_cable_tray_gauge_column_equals_the_planned_gauge():
    tray = tab(sample_workbook(sample_harnesses()), "Cable Tray")
    gauges = {cells[1] for index, cells in tray.items() if index > 1}
    assert gauges == {10}


def test_cable_tray_rows_sort_by_type_then_gauge_then_length():
    harnesses = sample_harnesses() + [engine.plan(engine.HarnessStringInput(
        module_count=4, module_pitch_m=2.0, trunk_tap_from_start_m=0.0,
        string_max_amps=90.0, is_tracker_row=True,
        requested_type=engine.PARALLEL_TRUNK))]
    summaries = engine.aggregate_harness_extensions(harnesses)
    keys = [(entry.type, entry.cable_gauge_awg, entry.drop_length_m) for entry in summaries]
    assert keys == sorted(keys)
    assert [entry.type for entry in summaries] == sorted(entry.type for entry in summaries)


def test_aggregate_quantises_to_one_millimetre():
    """Drops a micron apart are ONE bucket; a millimetre apart are two."""
    def harness(*drops):
        return engine.HarnessSpec(type=engine.END_OF_ROW, connectors=len(drops),
                                  cable_gauge_awg=10, module_drop_lengths_m=drops,
                                  total_cable_length_m=sum(drops))
    summaries = engine.aggregate_harness_extensions(
        [harness(1.0, 1.0000004), harness(1.001)])
    assert [(entry.drop_length_m, entry.count) for entry in summaries] == [(1.0, 2), (1.001, 1)]


def test_aggregate_refuses_a_null_list_and_skips_a_null_harness():
    with pytest.raises(engine.BomArgumentError):
        engine.aggregate_harness_extensions(None)
    assert engine.aggregate_harness_extensions([None]) == []


def test_cable_tray_empty_harnesses_has_headers_and_no_data_rows():
    tray = tab(sample_workbook([]), "Cable Tray")
    assert tray == {1: list(engine.CABLE_TRAY_HEADER)}


def test_cable_tray_null_harnesses_falls_back_to_the_placeholder():
    tray = tab(sample_workbook(None), "Cable Tray")
    assert tray == {1: [engine.CABLE_TRAY_PLACEHOLDER]}


def test_the_harness_overload_preserves_the_seven_tab_spec():
    assert tuple(name for name, _ in sample_workbook(sample_harnesses())) == engine.TAB_NAMES


def test_build_bom_workbook_refuses_a_missing_bom_or_rows():
    bom = engine.compute_bom(two_rows(), default_module())
    with pytest.raises(engine.BomArgumentError):
        engine.build_bom_workbook(None, two_rows())
    with pytest.raises(engine.BomArgumentError):
        engine.build_bom_workbook(bom, None)


def test_by_area_keeps_first_occurrence_group_order():
    """LINQ GroupBy orders by FIRST occurrence, so the two torque tube lines stay
    adjacent and the group order follows the BOM's own line order."""
    by_area = tab(sample_workbook(), "By Area")
    categories = [cells[0] for index, cells in sorted(by_area.items()) if index > 1]
    assert categories == ["Module", "Torque Tube", "Torque Tube", "Pile",
                          "Drive Unit", "DC Capacity"]


# --------------------------------------------------------------------------- #
# Layer 2: the licensed captures, reproduced by computing
# --------------------------------------------------------------------------- #
def test_the_generated_csv_equals_the_licensed_capture():
    reference = (REFERENCE_DIR / CSV_FILE).read_bytes().decode("ascii").replace("\r\n", "\n")
    assert generated(CSV_FILE).replace("\r\n", "\n") == reference


def test_the_generated_csv_uses_the_plugins_crlf_and_ascii():
    raw = probes.file_bytes(CSV_FILE, generated(CSV_FILE))
    assert raw.decode("ascii") == generated(CSV_FILE)
    assert raw.endswith(b"\r\n")
    assert raw.count(b"\n") == raw.count(b"\r\n") == 24
    assert max(raw) < 128


@pytest.mark.parametrize("label", sorted(
    csv_rows((REFERENCE_DIR / CSV_FILE).read_bytes().decode("ascii"))))
def test_every_licensed_harness_plan_probe_is_reproduced(label):
    """One assertion per scenario, so a failure names the scenario that moved."""
    reference = csv_rows((REFERENCE_DIR / CSV_FILE).read_bytes().decode("ascii"))[label]
    computed = csv_rows(generated(CSV_FILE))[label]
    assert computed == reference


def test_the_capture_holds_every_scenario_the_fixture_declares():
    reference = csv_rows((REFERENCE_DIR / CSV_FILE).read_bytes().decode("ascii"))
    assert sorted(reference) == sorted(label for label, _ in probes.HARNESSPLAN_SCENARIOS)
    assert len(reference) == 23


def test_the_three_refusal_rows_are_the_sanitized_messages():
    """The capture's dash is GONE, which is the ASCII filter doing its work."""
    reference = csv_rows((REFERENCE_DIR / CSV_FILE).read_bytes().decode("ascii"))
    assert reference["E1"]["ResultType"] == "ERROR_SUPPORT"
    assert reference["E1"]["Drops"] == (
        "Parallel trunk harness requires a tracker row  fixed-tilt rows lack "
        "the interior conduit path for in-row parallel taps.")
    assert reference["E3"]["ResultType"] == "ERROR_AMPS"
    assert reference["E2"]["CableGaugeAwg"] == ""


def test_sanitize_message_drops_non_ascii_and_neutralizes_the_delimiter():
    assert engine.sanitize_message("a \u2014 b") == "a  b"
    assert engine.sanitize_message("a|b\r\nc") == "a b  c"
    assert engine.sanitize_message("") == ""
    assert engine.sanitize_message(None) == ""


@pytest.mark.parametrize("name", WORKBOOK_FILES)
def test_the_generated_workbook_equals_the_licensed_capture(name):
    assert generated_workbook(name) == reference_workbook(name)


@pytest.mark.parametrize("name", WORKBOOK_FILES)
def test_the_generated_workbook_keeps_the_seven_tab_contract(name):
    assert tuple(sheet.name for sheet in generated_workbook(name)) == engine.TAB_NAMES


@pytest.mark.parametrize("name,sheet", [(name, sheet)
                                        for name in WORKBOOK_FILES
                                        for sheet in engine.TAB_NAMES])
def test_every_licensed_sheet_is_reproduced_row_for_row(name, sheet):
    """One assertion per sheet, so a failure names the tab that moved."""
    assert rows_of(generated_workbook(name), sheet) == rows_of(reference_workbook(name), sheet)


def test_the_licensed_empty_fixtures_pin_all_three_placeholders():
    f1 = reference_workbook("leafbomxlsxempty_demo_f1.xlsx")
    f2 = reference_workbook("leafbomxlsxempty_demo_f2.xlsx")
    assert rows_of(f1, "Cable Tray")[1] == [engine.CABLE_TRAY_PLACEHOLDER]
    assert rows_of(f2, "Cable Tray") == {1: list(engine.CABLE_TRAY_HEADER)}
    for workbook in (f1, f2):
        assert rows_of(workbook, "Electrical")[2] == [engine.ELECTRICAL_PLACEHOLDER]
        assert rows_of(workbook, "Piling")[2] == [engine.PILING_PLACEHOLDER]


def test_the_licensed_bom_workbook_carries_the_closed_form_totals():
    """3 rows x 10 slots x 600 Wp, 20 m each, 5 m c/c: the demo's own arithmetic."""
    overview = rows_of(reference_workbook("leafbomxlsx_demo.xlsx"), "Overview")
    assert [cells[:2] for index, cells in sorted(overview.items()) if index > 1] == [
        ["Total rows (sections)", 3], ["Total modules", 30],
        ["Total tube length", 60], ["Total piles", 12],
        ["Total drive units", 3], ["DC nameplate capacity", 18]]
    # The bucket formula says 12 and GeneratePileCoordinates says 15: both ends
    # of every row get a pile, which is deliberately a different count.
    assert len(rows_of(reference_workbook("leafbomxlsx_demo.xlsx"), "Piling")) == 16


def test_the_licensed_cable_tray_sums_to_the_demos_closed_form():
    """3 x (0+1+...+9) + 4.5 = 139.5 m, the HarnessBomDemoCommand header's number."""
    tray = rows_of(reference_workbook("leafharness_bom_demo.xlsx"), "Cable Tray")
    total = sum(cells[4] for index, cells in tray.items() if index > 1)
    assert total == pytest.approx(139.5, abs=1e-9)
    assert len(tray) == 12


def test_the_probe_maps_cover_every_file_the_demos_write():
    assert sorted(probes.FILE_CAPABILITIES) == sorted(ALL_FILES)
    assert sorted(probes.FILE_PROBE_TYPES) == sorted(ALL_FILES)
    assert sorted(probes.FILE_DEMOS) == sorted(ALL_FILES)
    assert all((REFERENCE_DIR / name).is_file() for name in ALL_FILES)


def test_writing_the_probe_files_reproduces_them_on_disk(tmp_path):
    """The CLI path, end to end: what `write` puts on disk is what the port computed."""
    for demo in sorted(probes.DEMOS):
        for path in probes.write(demo, tmp_path):
            assert path.name in ALL_FILES
    assert (tmp_path / CSV_FILE).read_bytes() == \
        probes.file_bytes(CSV_FILE, generated(CSV_FILE))
    for name in WORKBOOK_FILES:
        assert xlsx.read_workbook_file(tmp_path / name) == reference_workbook(name)


def test_an_unknown_demo_is_refused():
    with pytest.raises(ValueError):
        probes.build("nope")
    with pytest.raises(ValueError):
        probes.file_names("nope")


def test_the_cli_writes_every_file(tmp_path):
    assert probes.main(["--out-dir", str(tmp_path), "--all"]) == 0
    assert sorted(path.name for path in tmp_path.iterdir()) == sorted(ALL_FILES)


def test_the_cli_refuses_an_empty_demo_list(tmp_path):
    assert probes.main(["--out-dir", str(tmp_path)]) == 2


def test_no_capture_value_leaks_into_the_port():
    """Every drop is computed from the fixture, never read back from the file."""
    plan = engine.plan(engine.HarnessStringInput(
        module_count=10, module_pitch_m=1.0, trunk_tap_from_start_m=3.0,
        string_max_amps=20.0, is_tracker_row=True, requested_type=engine.END_OF_ROW))
    assert list(plan.module_drop_lengths_m) == [3, 2, 1, 0, 1, 2, 3, 4, 5, 6]
    assert math.isclose(plan.total_cable_length_m, 27.0)
