"""Studio's six terrain and irradiance engines against the licensed plugin, computed.

Two layers, all hermetic and none of them skipping:

  1. Every probe in the six licensed DEMO captures, reproduced by RUNNING
     Studio's fixtures through server/solar_terrain.py. The captures are the
     licensed AutoCAD 2025 run of 2026-09-23 and are COMMITTED at
     docs/parity/evidence/probes/demo-probes-20260923, so this layer reads the
     artifact itself rather than a transcription and every runner carries it.
     Each file is asserted whole, then probe by probe (one test per licensed
     row, collected from the committed file), so a failure names the row.
  2. The plugin's OWN unit tests for these engines, ported case for case from
     Tests/Tests/LeafHeatmapTests.cs, LeafHorizonProfileTests.cs,
     LeafInPlaneIrradianceTests.cs, LeafGradingPadTests.cs,
     LeafTerrainProfileTests.cs and LeafCapacityIterationTests.cs (read
     2026-09-23 at C:/tmp/solar-parity/wt-b25-s17). One case is omitted and
     named here rather than left as a silent gap:
     LeafGradingPadTests.CommandSource_RegistersInteractiveBuildAndPersistenceFlow
     greps the plugin's AutoCAD command source, which is not what this port
     covers. C# exception types map to Python ones: ArgumentNullException to
     TypeError, ArgumentException to ValueError, InvalidOperationException to
     solar_terrain.SiteOutsideTerrainError.

Line endings, and why the whole-file assertion normalizes them. The plugin
writes CRLF and this port writes CRLF, which
`test_the_generated_bytes_carry_the_plugins_encoding_and_crlf` asserts on the
GENERATED bytes. The committed capture is a tracked text file, so git's checkout
translation decides its on-disk line endings, and comparing against it byte for
byte would be asserting a git setting rather than a parity fact. The byte order
mark is not a line ending, so the whole-file assertion keeps it.

Nothing here feeds a captured value back into the port: solar_terrain.py
computes every number and renders every string, and these are the assertions it
must meet.
"""

from __future__ import annotations

import functools
import importlib.util
import math
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[2]


def _load(name, path):
    spec = importlib.util.spec_from_file_location(name, path)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


engine = _load("solar_terrain", ROOT / "server" / "solar_terrain.py")
probes = _load("solar_terrain_probes", ROOT / "scripts" / "solar_terrain_probes.py")

# The licensed capture is committed in this repo, so every runner carries it.
REFERENCE_DIR = ROOT / "docs/parity/evidence/probes/demo-probes-20260923"
ALL_FILES = tuple(name for demo in sorted(probes.DEMOS) for name in probes.file_names(demo))
BOM = b"\xef\xbb\xbf"
# Which files carry Encoding.UTF8's preamble: the four commands that pass it.
FILES_WITH_BOM = frozenset({"leafhorizon_demo.csv", "leafgradingpad_demo.csv",
                            "leafcrosssection_demo.csv", "leafcapacity_demo.csv"})


@functools.lru_cache(maxsize=None)
def generated_bytes(name):
    """Studio's own bytes for one file, computed from its fixture (once per run)."""
    content = probes.build(probes.FILE_DEMOS[name])[name]
    return probes.file_bytes(name, content)


def reference_bytes(name):
    return (REFERENCE_DIR / name).read_bytes()


def lf(data):
    return data.replace(b"\r\n", b"\n")


def data_rows(data):
    """(header cells, [row cells]) of one probe CSV: BOM and `#` preamble skipped."""
    text = data.decode("utf-8")
    if text.startswith("\ufeff"):
        text = text[1:]
    lines = [line for line in text.replace("\r\n", "\n").split("\n") if line]
    while lines and lines[0].startswith("#"):
        lines.pop(0)
    return lines[0].split(","), [line.split(",") for line in lines[1:]]


def _licensed_row_cases():
    """One (file, index) per licensed data row, read from the COMMITTED capture.

    Reading at collection means a missing capture is a collection error, never
    a skip, and a capture that gains or loses a row changes the case list.
    """
    cases = []
    for name in ALL_FILES:
        _, rows = data_rows(reference_bytes(name))
        cases.extend(pytest.param(name, index, id="%s:%d" % (name, index + 1))
                     for index in range(len(rows)))
    return cases


# --------------------------------------------------------------------------- #
# Layer 1: the licensed captures, reproduced by computation
# --------------------------------------------------------------------------- #
def test_every_licensed_file_is_committed_and_has_a_builder():
    """A subset check: this suite's own six files, never the folder's whole list."""
    for name in ALL_FILES:
        assert (REFERENCE_DIR / name).is_file(), name
    assert set(ALL_FILES) == set(probes.FILE_CAPABILITIES) == set(probes.FILE_PROBE_TYPES)


@pytest.mark.parametrize("name", ALL_FILES)
def test_the_generated_file_is_the_licensed_capture(name):
    assert lf(generated_bytes(name)) == lf(reference_bytes(name))


@pytest.mark.parametrize("name", ALL_FILES)
def test_the_generated_bytes_carry_the_plugins_encoding_and_crlf(name):
    data = generated_bytes(name)
    assert data.startswith(BOM) == (name in FILES_WITH_BOM)
    assert reference_bytes(name).startswith(BOM) == (name in FILES_WITH_BOM)
    assert data.endswith(b"\r\n")
    assert b"\n" not in data.replace(b"\r\n", b"")
    assert b"\r" not in data.replace(b"\r\n", b"")
    assert b'"' not in data
    if name == "leafheatmap_demo.csv":
        data.decode("ascii")


@pytest.mark.parametrize("name,index", _licensed_row_cases())
def test_every_licensed_probe_is_reproduced(name, index):
    ref_header, ref_rows = data_rows(reference_bytes(name))
    gen_header, gen_rows = data_rows(generated_bytes(name))
    assert gen_header == ref_header
    assert len(gen_rows) == len(ref_rows)
    assert dict(zip(gen_header, gen_rows[index])) == dict(zip(ref_header, ref_rows[index]))


def test_the_preambles_are_the_plugins():
    """The `#` lines are part of the file too; the grading pad's are computed."""
    text = generated_bytes("leafgradingpad_demo.csv").decode("utf-8")
    assert "# mid-edge z: S=0.750000 N=0.750000 W=0.500000 E=1.000000; uniform_ref=0.750000" \
        in text
    text = generated_bytes("leafhorizon_demo.csv").decode("utf-8")
    assert text.startswith("\ufeff# LEAFHORIZON far-shading horizon profile\r\n"
                           "# Site centre: (0.0000, 0.0000)\r\n")


def test_the_horizon_demo_meets_its_closed_form():
    """LEAFHORIZONDEMO's own anchor: atan(5/100) at az 0, zero everywhere else."""
    peak_row, peak_col, peak_m = probes.HORIZON_PEAK
    grid = probes._grid(probes.HORIZON_GRID,
                        lambda r, c, x, y: peak_m if (r, c) == (peak_row, peak_col) else 0.0)
    profile = engine.generate_horizon_profile(grid, 0.0, 0.0, observer_height_m=0.0,
                                              azimuth_step_deg=10.0, ray_step_du=1.0)
    assert len(profile) == 36
    # The peak node sits exactly on the az-0 ray at s = 100, so the sample is
    # exact; the plugin's RadToDeg constant, not 180/pi applied twice, is the
    # multiplier (the two can differ in the last bit).
    assert profile[0].elevation_deg == math.atan2(5.0, 100.0) * engine.RAD_TO_DEG
    assert all(sample.elevation_deg == 0.0 for sample in profile[1:])


def test_the_capacity_sort_is_most_dc_first_then_gcr_ascending():
    results = engine.enumerate_capacity(
        probes.CAPACITY_BOUNDARY, probes.capacity_module(),
        engine.CapacityRange(*probes.CAPACITY_GCR), engine.CapacityRange(*probes.CAPACITY_TILT),
        probes.CAPACITY_MAX_SCENARIOS)
    assert [(r.row_count, r.module_count, r.tilt_deg) for r in results[:2]] == \
        [(24, 1176, 20.0), (24, 1176, 50.0)]
    assert [r.dc_kwp for r in results] == sorted((r.dc_kwp for r in results), reverse=True)


def test_the_perez_bins_are_perez_table_one():
    assert [engine.perez_bin(e) for e in (1.0, 1.065, 1.23, 1.5, 1.95, 2.8, 4.5, 6.2, 9.0)] \
        == [1, 2, 3, 4, 5, 6, 7, 8, 8]
    assert len(engine.PEREZ_COEFFICIENTS_1990) == 8
    assert all(len(row) == 6 for row in engine.PEREZ_COEFFICIENTS_1990)


def test_the_cli_writes_every_file(tmp_path):
    assert probes.main(["--out-dir", str(tmp_path), "--all"]) == 0
    for name in ALL_FILES:
        assert (tmp_path / name).read_bytes() == generated_bytes(name)


def test_the_cli_refuses_no_demo(tmp_path, capsys):
    assert probes.main(["--out-dir", str(tmp_path)]) == 2
    assert "solar-terrain-probes" in capsys.readouterr().err


# --------------------------------------------------------------------------- #
# Layer 2a: LeafHeatmapTests.cs
# --------------------------------------------------------------------------- #
def heat_grid(elevs):
    """BuildGrid: extents (0,0)-(cols-1, rows-1), metersPerUnit 1."""
    rows, cols = len(elevs), len(elevs[0])
    flat = [value for row in elevs for value in row]
    return engine.TerrainGridInterpolator(flat, rows, cols, 0, cols - 1, 0, rows - 1, 1.0)


def test_heatmap_2x2_grid_returns_four_cells():
    cells = engine.compute_cells(heat_grid([[100.0, 102.0], [98.0, 101.0]]), 100.0)
    assert len(cells) == 4


def test_heatmap_proposed_at_min_is_all_cut_or_neutral():
    cells = engine.compute_cells(heat_grid([[100.0, 110.0], [105.0, 108.0]]), 100.0)
    assert all(cell.delta_m >= 0.0 for cell in cells)


def test_heatmap_proposed_at_max_is_all_fill_or_neutral():
    cells = engine.compute_cells(heat_grid([[100.0, 110.0], [105.0, 108.0]]), 110.0)
    assert all(cell.delta_m <= 0.0 for cell in cells)


def test_heatmap_delta_is_elevation_minus_proposed():
    cells = engine.compute_cells(heat_grid([[100.0, 106.0], [102.0, 108.0]]), 103.0)
    expected = sorted([100 - 103.0, 106 - 103.0, 102 - 103.0, 108 - 103.0])
    assert sorted(cell.delta_m for cell in cells) == pytest.approx(expected, abs=1e-9)


def test_heatmap_at_grade_delta_is_zero():
    cells = engine.compute_cells(heat_grid([[100.0, 100.0], [100.0, 100.0]]), 100.0)
    assert all(abs(cell.delta_m) <= 1e-9 for cell in cells)


def test_heatmap_cell_count_is_the_node_count():
    grid = heat_grid([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0], [7.0, 8.0, 9.0], [10.0, 11.0, 12.0]])
    assert len(engine.compute_cells(grid, 5.0)) == 12


def test_heatmap_half_width_and_height_are_half_the_node_spacing():
    cells = engine.compute_cells(
        heat_grid([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0], [7.0, 8.0, 9.0]]), 5.0)
    assert len(cells) == 9
    assert all(abs(c.half_width_du - 0.5) <= 1e-9 and abs(c.half_height_du - 0.5) <= 1e-9
               for c in cells)


def test_heatmap_max_abs_delta_is_the_largest():
    cells = engine.compute_cells(heat_grid([[95.0, 103.0], [107.0, 99.0]]), 100.0)
    assert engine.max_abs_delta_m(cells) == pytest.approx(7.0, abs=1e-9)


def test_heatmap_max_abs_delta_all_at_grade_is_zero():
    cells = engine.compute_cells(heat_grid([[100.0, 100.0], [100.0, 100.0]]), 100.0)
    assert engine.max_abs_delta_m(cells) == 0.0


def test_heatmap_null_interpolator_is_refused():
    with pytest.raises(TypeError):
        engine.compute_cells(None, 100.0)


def test_heatmap_shallow_fill_is_green_not_red():
    r, g, b = engine.compute_heat_rgb(-0.10)
    assert g == 255 and r < 255


def test_heatmap_shallow_fill_is_not_neutral_grey():
    assert engine.compute_heat_rgb(-0.10) != (210, 210, 210)


def test_heatmap_deep_fill_is_pure_green():
    assert engine.compute_heat_rgb(-3.0) == (0, 255, 0)


def test_heatmap_shallow_cut_is_red_with_fading_green_and_blue():
    r, g, b = engine.compute_heat_rgb(0.10)
    assert r == 255 and g < 255 and b < 255


def test_heatmap_at_grade_is_grey():
    assert engine.compute_heat_rgb(0.0) == (210, 210, 210)


# --------------------------------------------------------------------------- #
# Layer 2b: LeafHorizonProfileTests.cs
# --------------------------------------------------------------------------- #
def flat_grid(rows, cols, elevation):
    return engine.TerrainGridInterpolator([elevation] * (rows * cols), rows, cols,
                                          0, cols - 1, 0, rows - 1, 1.0)


def north_peak_grid():
    elevations = [0.0] * (11 * 11)
    elevations[10 * 11 + 5] = 10.0
    return engine.TerrainGridInterpolator(elevations, 11, 11, 0, 10, 0, 10)


def by_azimuth(profile, az):
    return next(s.elevation_deg for s in profile if abs(s.azimuth_deg - az) < 1e-6)


def test_horizon_null_terrain_is_refused():
    with pytest.raises(TypeError):
        engine.generate_horizon_profile(None, 0, 0)


def test_horizon_nonpositive_azimuth_step_is_refused():
    with pytest.raises(ValueError):
        engine.generate_horizon_profile(flat_grid(10, 10, 0), 5, 5, azimuth_step_deg=0.0)


def test_horizon_nonpositive_ray_step_is_refused():
    with pytest.raises(ValueError):
        engine.generate_horizon_profile(flat_grid(10, 10, 0), 5, 5, ray_step_du=0.0)


def test_horizon_site_outside_grid_is_refused():
    with pytest.raises(engine.SiteOutsideTerrainError):
        engine.generate_horizon_profile(flat_grid(10, 10, 0), 100, 100)


def test_horizon_flat_terrain_is_zero_everywhere():
    profile = engine.generate_horizon_profile(flat_grid(11, 11, 0), 5, 5, observer_height_m=1.5,
                                              azimuth_step_deg=10.0, ray_step_du=1.0)
    assert len(profile) == 36
    assert all(abs(s.elevation_deg) <= 1e-9 for s in profile)


def test_horizon_north_peak_matches_the_closed_form():
    profile = engine.generate_horizon_profile(north_peak_grid(), 5, 5, observer_height_m=0.0,
                                              azimuth_step_deg=1.0, ray_step_du=0.25)
    expected = math.atan2(10.0, 5.0) * 180.0 / math.pi
    assert by_azimuth(profile, 0) == pytest.approx(expected, abs=0.5)
    assert by_azimuth(profile, 180) == pytest.approx(0.0, abs=0.01)


def test_horizon_north_peak_leaves_east_and_west_clear():
    profile = engine.generate_horizon_profile(north_peak_grid(), 5, 5, observer_height_m=0,
                                              azimuth_step_deg=5)
    assert by_azimuth(profile, 90) == pytest.approx(0.0, abs=0.01)
    assert by_azimuth(profile, 270) == pytest.approx(0.0, abs=0.01)


def test_horizon_east_west_ridge_is_symmetric():
    e = [0.0] * 121
    for r in range(11):
        e[r * 11 + 0] = 5.0
        e[r * 11 + 10] = 5.0
    grid = engine.TerrainGridInterpolator(e, 11, 11, 0, 10, 0, 10)
    profile = engine.generate_horizon_profile(grid, 5, 5, observer_height_m=0,
                                              azimuth_step_deg=1, ray_step_du=0.25)
    for az in (30.0, 60.0, 90.0, 120.0):
        assert by_azimuth(profile, az) == pytest.approx(by_azimuth(profile, 360.0 - az), abs=0.1)


def test_horizon_north_south_ridge_is_symmetric():
    e = [0.0] * 121
    for c in range(11):
        e[0 * 11 + c] = 5.0
        e[10 * 11 + c] = 5.0
    grid = engine.TerrainGridInterpolator(e, 11, 11, 0, 10, 0, 10)
    profile = engine.generate_horizon_profile(grid, 5, 5, observer_height_m=0,
                                              azimuth_step_deg=1, ray_step_du=0.25)
    for az in (30.0, 60.0, 120.0, 150.0):
        mirror = math.fmod((180.0 - az) + 360.0, 360.0)
        assert by_azimuth(profile, az) == pytest.approx(by_azimuth(profile, mirror), abs=0.1)


def test_horizon_profile_count_is_360_over_step():
    grid = flat_grid(10, 10, 0)
    assert [len(engine.generate_horizon_profile(grid, 5, 5, azimuth_step_deg=step))
            for step in (1, 5, 10)] == [360, 72, 36]


def test_horizon_sun_above_the_peak_is_not_blocked():
    profile = engine.generate_horizon_profile(north_peak_grid(), 5, 5, observer_height_m=0,
                                              azimuth_step_deg=1)
    assert engine.is_sun_below_horizon(profile, 0, 85) is False


def test_horizon_sun_behind_the_peak_is_blocked():
    profile = engine.generate_horizon_profile(north_peak_grid(), 5, 5, observer_height_m=0,
                                              azimuth_step_deg=1, ray_step_du=0.25)
    assert engine.is_sun_below_horizon(profile, 0, 30) is True


def test_horizon_null_or_empty_profile_never_blocks():
    assert engine.is_sun_below_horizon(None, 0, 10) is False
    assert engine.is_sun_below_horizon([], 0, 10) is False


def test_horizon_sun_azimuth_is_normalised():
    profile = engine.generate_horizon_profile(north_peak_grid(), 5, 5, observer_height_m=0,
                                              azimuth_step_deg=1, ray_step_du=0.25)
    assert engine.is_sun_below_horizon(profile, 720, 30) is True
    assert engine.is_sun_below_horizon(profile, -360, 30) is True


# --------------------------------------------------------------------------- #
# Layer 2c: LeafInPlaneIrradianceTests.cs (isotropic, HDKR, Perez)
# --------------------------------------------------------------------------- #
NUMERIC = 1e-6
RELIABLE = 1e-9
iso = engine.compute_isotropic
hdkr = engine.compute_hdkr
perez = engine.compute_perez


def test_isotropic_horizontal_returns_ghi():
    ghi = 800.0 * math.cos(30.0 * math.pi / 180.0) + 200.0
    poa = iso(800.0, 200.0, ghi, 30.0, 180.0, 0.0, 180.0)
    assert poa.global_irradiance == pytest.approx(ghi, abs=NUMERIC)
    assert poa.sky_diffuse == pytest.approx(200.0, abs=NUMERIC)
    assert poa.ground_diffuse == pytest.approx(0.0, abs=NUMERIC)


def test_isotropic_vertical_sky_diffuse_is_half_dhi():
    assert iso(0, 400, 400, 45, 180, 90, 180).sky_diffuse == pytest.approx(200.0, abs=NUMERIC)


def test_isotropic_vertical_ground_diffuse_is_half_albedo_ghi():
    poa = iso(0, 0, 1000, 45, 180, 90, 0, albedo=0.3)
    assert poa.ground_diffuse == pytest.approx(150.0, abs=NUMERIC)


def test_isotropic_direct_at_aoi_zero_is_dni():
    ghi = 1000.0 * math.cos(35.0 * math.pi / 180.0)
    assert iso(1000, 0, ghi, 35.0, 180, 35.0, 180).direct == pytest.approx(1000.0, abs=NUMERIC)


def test_isotropic_azimuth_offsets_are_symmetric():
    east = iso(700, 150, 700, 40, 180, 30, 150)
    west = iso(700, 150, 700, 40, 180, 30, 210)
    assert east.direct == pytest.approx(west.direct, abs=NUMERIC)
    assert east.sky_diffuse == pytest.approx(west.sky_diffuse, abs=NUMERIC)
    assert east.ground_diffuse == pytest.approx(west.ground_diffuse, abs=NUMERIC)


def test_isotropic_sun_behind_panel_clips_direct_only():
    poa = iso(900, 100, 800, 30, 180, 90, 0)
    assert poa.direct == pytest.approx(0.0, abs=RELIABLE)
    assert poa.sky_diffuse > 0.0 and poa.ground_diffuse > 0.0


def test_isotropic_sky_diffuse_falls_with_tilt():
    previous = math.inf
    for tilt in range(0, 181, 15):
        sky = iso(0, 300, 300, 45, 180, tilt, 180).sky_diffuse
        assert sky <= previous + NUMERIC
        previous = sky


def test_isotropic_ground_diffuse_rises_with_tilt():
    previous = -math.inf
    for tilt in range(0, 181, 15):
        ground = iso(0, 0, 800, 45, 180, tilt, 180, albedo=0.25).ground_diffuse
        assert ground >= previous - NUMERIC
        previous = ground


def test_isotropic_global_is_the_sum_of_components():
    poa = iso(800, 180, 870, 35, 180, 25, 180, albedo=0.2)
    assert poa.global_irradiance == pytest.approx(
        poa.direct + poa.sky_diffuse + poa.ground_diffuse, abs=RELIABLE)


def test_isotropic_all_zero_inputs_are_all_zero():
    poa = iso(0, 0, 0, 45, 180, 30, 180)
    assert (poa.direct, poa.sky_diffuse, poa.ground_diffuse, poa.global_irradiance) == \
        (0.0, 0.0, 0.0, 0.0)


@pytest.mark.parametrize("args,kwargs", [
    ((-1, 0, 0, 45, 180, 30, 180), {}),
    ((0, -1, 0, 45, 180, 30, 180), {}),
    ((0, 0, -1, 45, 180, 30, 180), {}),
    ((0, 0, 0, 45, 180, -1, 180), {}),
    ((0, 0, 0, 45, 180, 181, 180), {}),
    ((0, 0, 0, 45, 180, 30, 180), {"albedo": -0.1}),
    ((0, 0, 0, 45, 180, 30, 180), {"albedo": 1.1}),
], ids=["dni", "dhi", "ghi", "tilt-low", "tilt-high", "albedo-low", "albedo-high"])
def test_isotropic_refuses_out_of_domain_inputs(args, kwargs):
    with pytest.raises(ValueError):
        iso(*args, **kwargs)


def test_hdkr_zero_dni_reduces_to_isotropic():
    a = iso(0, 300, 300, 45, 180, 30, 180)
    b = hdkr(0, 300, 300, 45, 180, 30, 180, 80)
    assert (b.direct, b.sky_diffuse, b.ground_diffuse) == pytest.approx(
        (a.direct, a.sky_diffuse, a.ground_diffuse), abs=NUMERIC)


def test_hdkr_horizontal_returns_ghi():
    ghi = 800.0 * math.cos(30.0 * math.pi / 180.0) + 200.0
    assert hdkr(800.0, 200.0, ghi, 30.0, 180, 0, 180, 172).global_irradiance == \
        pytest.approx(ghi, abs=NUMERIC)


def test_hdkr_beats_isotropic_under_clear_sky():
    ghi = 950 * math.cos(35 * math.pi / 180.0) + 80
    a = iso(950, 80, ghi, 35, 180, 30, 180)
    b = hdkr(950, 80, ghi, 35, 180, 30, 180, 172)
    assert b.global_irradiance > a.global_irradiance + 1.0
    assert b.direct == pytest.approx(a.direct, abs=NUMERIC)
    assert b.ground_diffuse == pytest.approx(a.ground_diffuse, abs=NUMERIC)


def test_hdkr_equals_isotropic_when_overcast():
    a = iso(0, 250, 250, 60, 180, 35, 200)
    b = hdkr(0, 250, 250, 60, 180, 35, 200, 1)
    assert b.global_irradiance == pytest.approx(a.global_irradiance, abs=NUMERIC)


def test_hdkr_azimuth_offsets_are_symmetric():
    east = hdkr(700, 150, 700, 40, 180, 30, 150, 172)
    west = hdkr(700, 150, 700, 40, 180, 30, 210, 172)
    assert east.global_irradiance == pytest.approx(west.global_irradiance, abs=NUMERIC)


def test_hdkr_sun_behind_panel_drops_the_circumsolar_share():
    poa = hdkr(900, 100, 800, 30, 180, 90, 0, 172)
    assert poa.direct == pytest.approx(0.0, abs=RELIABLE)
    assert poa.sky_diffuse > 0.0


def test_hdkr_anisotropy_index_is_clipped():
    poa = hdkr(2000, 50, 1700, 30, 180, 30, 180, 172)
    assert poa.sky_diffuse >= 0.0 and not math.isnan(poa.sky_diffuse)


@pytest.mark.parametrize("model", [hdkr, perez], ids=["hdkr", "perez"])
@pytest.mark.parametrize("day", [0, 367])
def test_day_of_year_out_of_range_is_refused(model, day):
    with pytest.raises(ValueError):
        model(500, 100, 500, 45, 180, 30, 180, day)


@pytest.mark.parametrize("model", [hdkr, perez], ids=["hdkr", "perez"])
@pytest.mark.parametrize("args,kwargs", [
    ((-1, 0, 0, 45, 180, 30, 180), {}),
    ((0, 0, 0, 45, 180, 181, 180), {}),
    ((0, 0, 0, 45, 180, 30, 180), {"albedo": -0.1}),
], ids=["dni", "tilt", "albedo"])
def test_anisotropic_models_inherit_isotropic_validation(model, args, kwargs):
    with pytest.raises(ValueError):
        model(*args, 1, **kwargs)


def test_perez_horizontal_returns_ghi():
    ghi = 800.0 * math.cos(30.0 * math.pi / 180.0) + 200.0
    assert perez(800.0, 200.0, ghi, 30.0, 180, 0, 180, 172).global_irradiance == \
        pytest.approx(ghi, abs=1e-6)


def test_perez_zero_dhi_zeroes_the_sky_diffuse():
    poa = perez(900, 0, 800, 30, 180, 30, 180, 172)
    assert poa.sky_diffuse == pytest.approx(0.0, abs=1e-12)
    assert poa.direct > 0.0 and poa.ground_diffuse > 0.0


def test_perez_sun_below_horizon_falls_back_to_isotropic():
    a = iso(0, 50, 50, 95.0, 180, 30, 180)
    b = perez(0, 50, 50, 95.0, 180, 30, 180, 172)
    assert (b.direct, b.sky_diffuse, b.ground_diffuse) == pytest.approx(
        (a.direct, a.sky_diffuse, a.ground_diffuse), abs=1e-9)


def test_perez_direct_and_ground_are_isotropic():
    a = iso(850, 150, 820, 40, 170, 25, 190, albedo=0.25)
    b = perez(850, 150, 820, 40, 170, 25, 190, 100, albedo=0.25)
    assert b.direct == pytest.approx(a.direct, abs=1e-9)
    assert b.ground_diffuse == pytest.approx(a.ground_diffuse, abs=1e-9)


def test_perez_azimuth_offsets_are_symmetric():
    east = perez(700, 150, 700, 40, 180, 30, 150, 172)
    west = perez(700, 150, 700, 40, 180, 30, 210, 172)
    assert east.global_irradiance == pytest.approx(west.global_irradiance, abs=1e-6)


def test_perez_clear_sky_boulder_matches_the_hand_calculation():
    poa = perez(800, 100, 825, 25, 190, 30, 180, 172, albedo=0.2)
    assert poa.direct == pytest.approx(794.34, abs=1.0)
    assert poa.sky_diffuse == pytest.approx(109.65, abs=2.0)
    assert poa.ground_diffuse == pytest.approx(11.06, abs=0.5)
    assert poa.global_irradiance == pytest.approx(915.05, abs=3.0)


def test_perez_clear_sky_boulder_beats_isotropic():
    a = iso(800, 100, 825, 25, 190, 30, 180)
    b = perez(800, 100, 825, 25, 190, 30, 180, 172)
    assert b.global_irradiance > a.global_irradiance + 3.0


def test_perez_thin_overcast_tracks_isotropic():
    a = iso(0, 50, 50, 60, 180, 30, 180)
    b = perez(0, 50, 50, 60, 180, 30, 180, 1)
    assert abs(b.global_irradiance - a.global_irradiance) < 3.0


def test_perez_all_zero_inputs_are_all_zero():
    poa = perez(0, 0, 0, 45, 180, 30, 180, 1)
    assert (poa.direct, poa.sky_diffuse, poa.ground_diffuse) == pytest.approx(
        (0.0, 0.0, 0.0), abs=1e-12)


# --------------------------------------------------------------------------- #
# Layer 2d: LeafGradingPadTests.cs
# --------------------------------------------------------------------------- #
Pad = engine.PadRectangle


@pytest.mark.parametrize("bounds", [(10, 0, 5, 10), (0, 10, 10, 5)], ids=["x", "y"])
def test_pad_rectangle_inverted_bounds_are_refused(bounds):
    with pytest.raises(ValueError):
        Pad(*bounds)


def test_pad_rectangle_corners_run_ccw_from_sw():
    assert Pad(0, 0, 10, 10).corners() == ((0.0, 0.0), (10.0, 0.0), (10.0, 10.0), (0.0, 10.0))


def test_q19_acceptance_one_metre_above_at_2h1v_matches_all_four_corners():
    r = engine.compute_embankment_toes(Pad(0, 0, 10, 10), 100.0, 99.0, 2.0, 1.0)
    assert r.horizontal_run_m == pytest.approx(2.0, abs=1e-9)
    assert r.height_delta_m == pytest.approx(1.0, abs=1e-9)
    assert [c for corner in r.corners_du for c in corner] == pytest.approx(
        [-2.0, -2.0, 12.0, -2.0, 12.0, 12.0, -2.0, 12.0], abs=1e-9)


def test_pad_below_terrain_still_runs_outward():
    r = engine.compute_embankment_toes(Pad(0, 0, 10, 10), 99.0, 100.0, 2.0)
    assert r.horizontal_run_m == pytest.approx(2.0, abs=1e-9)
    assert r.height_delta_m == pytest.approx(-1.0, abs=1e-9)
    assert r.corners_du[0][0] == pytest.approx(-2.0, abs=1e-9)


def test_zero_height_toe_is_the_pad_edge():
    r = engine.compute_embankment_toes(Pad(0, 0, 10, 10), 100.0, 100.0, 3.0)
    assert r.horizontal_run_m == pytest.approx(0.0, abs=1e-9)
    assert r.corners_du[0] == (0.0, 0.0)
    assert r.corners_du[2] == (10.0, 10.0)


def test_feet_drawing_units_scale_the_run():
    r = engine.compute_embankment_toes(Pad(0, 0, 10, 10), 100.0, 99.0, 2.0, 0.3048)
    assert r.horizontal_run_m == pytest.approx(2.0, abs=1e-9)
    assert r.corners_du[0] == pytest.approx((-2.0 / 0.3048, -2.0 / 0.3048), abs=1e-9)


@pytest.mark.parametrize("slope,mpu", [(-1.0, 1.0), (2.0, 0.0)], ids=["slope", "scale"])
def test_embankment_refuses_out_of_domain_parameters(slope, mpu):
    with pytest.raises(ValueError):
        engine.compute_embankment_toes(Pad(0, 0, 10, 10), 100, 99, slope, mpu)


def test_per_edge_on_flat_terrain_matches_uniform():
    grid = engine.TerrainGridInterpolator([99.0] * 4, 2, 2, 0, 20, 0, 20, 1.0)
    pad = Pad(5, 5, 15, 15)
    uniform = engine.compute_embankment_toes(pad, 100.0, 99.0, 2.0, 1.0)
    per_edge = engine.compute_embankment_toes_per_edge(pad, 100.0, grid, 2.0, 1.0)
    for a, b in zip(per_edge.corners_du, uniform.corners_du):
        assert a == pytest.approx(b, abs=1e-9)


def test_per_edge_on_an_east_slope_is_asymmetric():
    grid = engine.TerrainGridInterpolator([96.0, 100.0, 96.0, 100.0], 2, 2, 0, 100, 0, 100, 1.0)
    pad = Pad(40, 40, 60, 60)
    r = engine.compute_embankment_toes_per_edge(pad, 100.0, grid, 2.0, 1.0)
    assert pad.min_x - r.corners_du[0][0] == pytest.approx(4.8, abs=1e-9)
    assert r.corners_du[1][0] - pad.max_x == pytest.approx(3.2, abs=1e-9)
    assert pad.min_y - r.corners_du[0][1] == pytest.approx(4.0, abs=1e-9)


def test_per_edge_null_terrain_is_refused():
    with pytest.raises(TypeError):
        engine.compute_embankment_toes_per_edge(Pad(0, 0, 10, 10), 100.0, None, 2.0, 1.0)


# --------------------------------------------------------------------------- #
# Layer 2e: LeafTerrainProfileTests.cs
# --------------------------------------------------------------------------- #
def flat10():
    return engine.TerrainGridInterpolator([10.0] * 4, 2, 2, 0, 100, 0, 100, 1.0)


def sinusoidal_ridge():
    elevations = [1.0 * math.sin(2.0 * math.pi * (c * 10.0) / 100.0)
                  for r in range(11) for c in range(11)]
    return engine.TerrainGridInterpolator(elevations, 11, 11, 0, 100.0, 0, 100.0, 1.0)


def test_sample_line_null_terrain_is_refused():
    with pytest.raises(TypeError):
        engine.sample_line(None, (0, 0), (10, 0), 5)


@pytest.mark.parametrize("count", [0, -1])
def test_sample_line_nonpositive_count_is_refused(count):
    with pytest.raises(ValueError):
        engine.sample_line(flat10(), (0, 0), (10, 0), count)


def test_sample_line_single_sample_is_the_start_at_zero_distance():
    result = engine.sample_line(flat10(), (50, 50), (90, 90), 1)
    assert len(result) == 1
    assert result[0].distance_m == pytest.approx(0.0, abs=1e-9)
    assert result[0].elevation_m == pytest.approx(10.0, abs=0.01)
    assert (result[0].drawing_x, result[0].drawing_y) == (50.0, 50.0)


def test_sample_line_count_and_end_distances():
    result = engine.sample_line(flat10(), (0, 50), (100, 50), 11)
    assert len(result) == 11
    assert result[0].distance_m == pytest.approx(0.0, abs=1e-9)
    tail = engine.sample_line(flat10(), (10, 50), (40, 50), 5)
    assert tail[-1].distance_m == pytest.approx(30.0, abs=0.001)


def test_sample_line_flat_terrain_is_flat():
    result = engine.sample_line(flat10(), (10, 10), (90, 90), 10)
    assert all(p.elevation_m == pytest.approx(10.0, abs=0.01) for p in result)


def test_sample_line_off_grid_is_nan():
    assert math.isnan(engine.sample_line(flat10(), (50, 50), (200, 50), 3)[-1].elevation_m)


def test_sample_line_distances_increase():
    result = engine.sample_line(flat10(), (0, 0), (100, 100), 6)
    assert all(b.distance_m > a.distance_m for a, b in zip(result, result[1:]))


@pytest.mark.parametrize("terrain,vertices,samples,error", [
    (None, [(0, 0), (10, 0)], 3, TypeError),
    ("flat", None, 3, TypeError),
    ("flat", [(0, 0)], 3, ValueError),
    ("flat", [(0, 0), (10, 0)], 0, ValueError),
], ids=["terrain", "vertices", "one-vertex", "zero-samples"])
def test_sample_polyline_refuses_bad_arguments(terrain, vertices, samples, error):
    with pytest.raises(error):
        engine.sample_polyline(flat10() if terrain else None, vertices, samples)


def test_sample_polyline_two_segments():
    result = engine.sample_polyline(flat10(), [(0, 50), (50, 50), (100, 50)], 5)
    assert len(result) == 11
    assert all(b.distance_m > a.distance_m for a, b in zip(result, result[1:]))
    assert result[-1].distance_m == pytest.approx(100.0, abs=0.001)


def test_sample_polyline_single_segment_matches_sample_line():
    poly = engine.sample_polyline(flat10(), [(10, 10), (90, 10)], 6)
    line = engine.sample_line(flat10(), (10, 10), (90, 10), 7)
    assert len(poly) == len(line) == 7


def test_q20_sinusoid_error_is_under_five_centimetres():
    profile = engine.sample_line(sinusoidal_ridge(), (0.0, 50.0), (100.0, 50.0), 201)
    worst = max(abs(p.elevation_m - math.sin(2.0 * math.pi * p.drawing_x / 100.0))
                for p in profile)
    assert worst <= 0.05


def test_q20_sinusoid_is_exact_at_grid_nodes():
    profile = engine.sample_line(sinusoidal_ridge(), (0.0, 50.0), (100.0, 50.0), 11)
    for p in profile:
        assert p.elevation_m == pytest.approx(
            math.sin(2.0 * math.pi * p.drawing_x / 100.0), abs=1e-12)


def test_q20_mid_cell_error_matches_the_closed_form():
    profile = engine.sample_line(sinusoidal_ridge(), (5.0, 50.0), (5.0, 50.0), 1)
    actual = math.sin(2.0 * math.pi * 5.0 / 100.0) - profile[0].elevation_m
    expected = math.sin(math.pi * 10.0 / 100.0) - math.sin(2.0 * math.pi * 10.0 / 100.0) / 2.0
    assert actual == pytest.approx(expected, abs=1e-9)


# --------------------------------------------------------------------------- #
# Layer 2f: LeafCapacityIterationTests.cs
# --------------------------------------------------------------------------- #
Range = engine.CapacityRange
LEAFSAT_BOUNDARY = ((0.0, 0.0), (15.24, 0.0), (15.24, 30.48), (0.0, 30.48))
SQUARE = ((0.0, 0.0), (100.0, 0.0), (100.0, 100.0), (0.0, 100.0))


def standard_module():
    return engine.TrackerModuleSpec(along_axis_m=1.000, cross_axis_m=2.100, gap_m=0.020,
                                    rail_overhang_m=0.0, corridor_gap_m=0.0, pmax_w=600.0)


def sweep(boundary, gcr, tilt, cap):
    return engine.enumerate_capacity(boundary, standard_module(), Range(*gcr), Range(*tilt), cap)


def test_capacity_null_boundary_and_module_are_refused():
    with pytest.raises(TypeError):
        sweep(None, (0.30, 0.50, 3), (20.0, 40.0, 3), 100)
    with pytest.raises(TypeError):
        engine.enumerate_capacity(LEAFSAT_BOUNDARY, None, Range(0.30, 0.50, 3),
                                  Range(20.0, 40.0, 3), 100)


@pytest.mark.parametrize("gcr", [(0.0, 0.50, 3), (0.30, 1.5, 3)], ids=["zero", "above-one"])
def test_capacity_gcr_outside_zero_to_one_is_refused(gcr):
    with pytest.raises(ValueError):
        sweep(SQUARE, gcr, (20.0, 40.0, 3), 100)


def test_capacity_range_count_below_one_is_refused():
    with pytest.raises(ValueError):
        Range(0.30, 0.50, 0)


def test_capacity_more_than_the_cap_is_refused():
    with pytest.raises(ValueError):
        sweep(SQUARE, (0.30, 0.50, 11), (10.0, 60.0, 11), 100)


def test_capacity_exactly_the_cap_succeeds():
    assert len(sweep(SQUARE, (0.30, 0.50, 10), (10.0, 60.0, 10), 100)) == 100


def test_capacity_leafsat_regression_is_three_rows():
    results = sweep(LEAFSAT_BOUNDARY, (0.40, 0.40, 1), (30.0, 30.0, 1), 10)
    assert len(results) == 1 and results[0].row_count == 3


def test_capacity_pitch_is_cross_axis_over_gcr():
    assert sweep(SQUARE, (0.40, 0.40, 1), (30.0, 30.0, 1), 10)[0].pitch_m == \
        pytest.approx(2.1 / 0.40, abs=1e-9)


def test_capacity_row_count_rises_with_gcr():
    by_gcr = sorted(sweep(SQUARE, (0.20, 0.60, 9), (30.0, 30.0, 1), 100),
                    key=lambda r: r.gcr_target)
    assert all(b.row_count >= a.row_count for a, b in zip(by_gcr, by_gcr[1:]))
    assert by_gcr[0].row_count < by_gcr[-1].row_count


def test_capacity_module_count_is_rows_times_slots():
    r = sweep(SQUARE, (0.40, 0.40, 1), (30.0, 30.0, 1), 10)[0]
    assert r.module_count % r.row_count == 0
    assert r.module_count // r.row_count == 98


def test_capacity_dc_kwp_is_modules_times_pmax():
    for r in sweep(SQUARE, (0.30, 0.50, 3), (25.0, 35.0, 2), 20):
        assert r.dc_kwp == pytest.approx(r.module_count * 600.0 / 1000.0, abs=1e-9)


def test_capacity_acres_are_the_shoelace_area():
    r = sweep(SQUARE, (0.40, 0.40, 1), (30.0, 30.0, 1), 10)[0]
    assert r.acres_used == pytest.approx(10_000.0 / 4046.8564224, abs=1e-6)


def test_capacity_output_is_the_cartesian_product():
    results = sweep(SQUARE, (0.30, 0.50, 5), (10.0, 40.0, 4), 20)
    assert len(results) == 20
    distinct = sweep(SQUARE, (0.30, 0.50, 3), (20.0, 40.0, 3), 20)
    assert len({(r.gcr_target, r.tilt_deg) for r in distinct}) == len(distinct)


def test_capacity_results_are_sorted_by_dc_descending():
    results = sweep(SQUARE, (0.30, 0.50, 5), (25.0, 35.0, 2), 20)
    assert all(b.dc_kwp <= a.dc_kwp for a, b in zip(results, results[1:]))


def test_capacity_range_is_an_inclusive_linspace():
    values = Range(0.30, 0.50, 5).values()
    assert len(values) == 5
    assert values[0] == pytest.approx(0.30, abs=1e-12)
    assert values[-1] == pytest.approx(0.50, abs=1e-12)
    assert values[1] - values[0] == pytest.approx(0.05, abs=1e-12)
    assert values[2] - values[1] == pytest.approx(0.05, abs=1e-12)
    assert Range(0.40, 0.40, 1).values() == [0.40]
